CREATE TABLE ACCESSES --Description: Lab Access Requests
   (	ACCESS_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	PROP_ID VARCHAR2(15), 
	ARRIVAL DATE, 
	DEPARTURE DATE, 
	USER_TYPE VARCHAR2(5) NOT NULL ENABLE, 
	BML_NAME VARCHAR2(30), 
	STATUS VARCHAR2(1) NOT NULL ENABLE, 
	INS_ID NUMBER, 
	SUBMISSION_DATE DATE NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(400), 
	LAB_NAME VARCHAR2(100), 
	RESEARCHER_TYPE VARCHAR2(4), 
	GUEST_NET VARCHAR2(1), 
	FACILITY VARCHAR2(1), 
	VIDEO_ELETTRA VARCHAR2(1), 
	VIDEO_FERMI VARCHAR2(1), 
	 CONSTRAINT PK_ACCESSES PRIMARY KEY (ACCESS_ID)
    
	 CONSTRAINT FK_ACCESSES_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE, 
	 CONSTRAINT FK_INS_ID FOREIGN KEY (INS_ID)
	  REFERENCES INSTITUTES (ID) ENABLE
);

	COMMENT ON COLUMN ACCESSES.STATUS IS 'Label=Status, List=select code, description from list_of_values where list = ''AccessStatus'''
	COMMENT ON COLUMN ACCESSES.USER_TYPE IS 'Label=Status, List=select code, description from list_of_values where list = ''UserTypes'''
--------------------------------------------------------

CREATE TABLE ACTIONS 
   (	ID NUMBER NOT NULL ENABLE, 
	ACT_WHEN DATE NOT NULL ENABLE, 
	ACT_WHERE VARCHAR2(255) NOT NULL ENABLE, 
	WHAT VARCHAR2(20) NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	QUERY_STRING VARCHAR2(4000), 
	IPADDR VARCHAR2(15), 
	REAL_USR_ID NUMBER, 
	 CONSTRAINT ACT_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE ALLOCATION_END 
   (	USR_ID NUMBER, 
	BML_NAME VARCHAR2(25), 
	EVENT_DATE DATE, 
	NOT_SCHEDULED NUMBER, 
	TOTAL_PROP NUMBER, 
	 CONSTRAINT ALLOCATION_END_BEAMLINES_FK1 FOREIGN KEY (BML_NAME)
	  REFERENCES BEAMLINES (NAME) ENABLE, 
	 CONSTRAINT FK_ALLOCATION_END_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE AMM_SP01TPR 
   (	CODTIPO VARCHAR2(1), 
	DESCRTIPO VARCHAR2(20), 
	ORGANIGR VARCHAR2(1), 
	INFORZE VARCHAR2(1)
);
--------------------------------------------------------

CREATE TABLE AUDIT_SUP_PERSONAL_DATA_FORM_T 
   (	ID NUMBER, 
	USR_ID NUMBER, 
	REG_DATE DATE, 
	CASE1A VARCHAR2(10), 
	CASE2A VARCHAR2(10), 
	CASE2B VARCHAR2(10), 
	CASE3A VARCHAR2(10), 
	CASE3B VARCHAR2(10), 
	CASE4A VARCHAR2(10), 
	CASE5A VARCHAR2(10), 
	CASE5B VARCHAR2(10), 
	CASE6A VARCHAR2(10), 
	CASE6B VARCHAR2(10), 
	CASE7A VARCHAR2(10), 
	CASE7B VARCHAR2(10), 
	CASE8A VARCHAR2(10), 
	CASE8B VARCHAR2(10), 
	AUD_WHO NUMBER, 
	AUD_DATE DATE, 
	AUD_OPERATION VARCHAR2(1)
);
--------------------------------------------------------

CREATE TABLE AUDIT_USERS 
   (	ID NUMBER, 
	NAME VARCHAR2(40), 
	LASTNAME VARCHAR2(40), 
	EMAIL VARCHAR2(255), 
	URL VARCHAR2(255), 
	STATUS VARCHAR2(1), 
	PASSWORD VARCHAR2(20), 
	MAILING VARCHAR2(1), 
	INS_ID NUMBER, 
	PRIVACY VARCHAR2(1), 
	GENDER VARCHAR2(2), 
	NATIONALITY VARCHAR2(4), 
	BIRTH DATE, 
	COMP_1 VARCHAR2(2), 
	COMP_2 VARCHAR2(2), 
	RESEARCHER_TYPE VARCHAR2(4), 
	NEW_USER VARCHAR2(2), 
	BIRTH_CITY VARCHAR2(50), 
	BIRTH_CNT_ID VARCHAR2(4), 
	HOME_ADDR VARCHAR2(50), 
	HOME_CITY VARCHAR2(50), 
	HOME_CNT_ID VARCHAR2(4), 
	HOME_ZIP VARCHAR2(10), 
	SAFETY_VIDEO DATE, 
	COD_FISCALE VARCHAR2(16), 
	BIRTH_PROVINCE VARCHAR2(2), 
	BIRTH_TOWN VARCHAR2(50), 
	HOME_PROVINCE VARCHAR2(2), 
	HOME_TOWN VARCHAR2(50), 
	IDSUBJECT VARCHAR2(16), 
	CREATION_DATE DATE, 
	LAST_ACCESS DATE, 
	EAAHASH VARCHAR2(40), 
	AUD_WHEN DATE, 
	AUD_WHO VARCHAR2(200), 
	AUD_OPERATION VARCHAR2(1), 
	SEQ_NUM NUMBER NOT NULL ENABLE, 
	AUD_ADM_WHO VARCHAR2(200), 
	 CONSTRAINT AUDIT_USERS_PK PRIMARY KEY (SEQ_NUM)
);
--------------------------------------------------------

CREATE TABLE BALLOTS 
   (	VOTER_ID NUMBER, 
	CANDIDATE_ID NUMBER, 
	BALLOTS_YEAR VARCHAR2(4)
);
--------------------------------------------------------

CREATE TABLE BANKING 
   (	USR_ID NUMBER, 
	BANKING_ID NUMBER, 
	BANK_NAME VARCHAR2(50), 
	BANK_ADDRESS VARCHAR2(40), 
	ACCOUNT VARCHAR2(15), 
	IBAN VARCHAR2(30), 
	SWIFT VARCHAR2(30), 
	ACC_HOLDER VARCHAR2(60), 
	BANK_CITY VARCHAR2(40), 
	BANK_CNT_ID VARCHAR2(4), 
	 CONSTRAINT FK_BANKING_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
   );
--------------------------------------------------------

CREATE TABLE BEAMLINES 
   (	NAME VARCHAR2(25) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(80), 
	HOMEPAGE VARCHAR2(1024), 
	OPERATIVE VARCHAR2(1) NOT NULL ENABLE, -- Operative: Y = Yes, N = No
	REF_NATION VARCHAR2(4), 
	SHORT_NAME VARCHAR2(10), 
	IH_RESEARCH_PERC NUMBER, 
	FRONTEND VARCHAR2(6), 
	VIDEO_ID NUMBER, 
	FRACTION VARCHAR2(10), 
	DEFAULT_CMT_ID VARCHAR2(16), 
	FACILITY VARCHAR2(1), 
	 CONSTRAINT BML_PK PRIMARY KEY (NAME)
    
	 CONSTRAINT BEAMLINES_UK1 UNIQUE (SHORT_NAME)
   
   ); 
   COMMENT ON COLUMN BEAMLINES.NAME IS 'Label=Beamline Name'
   COMMENT ON COLUMN BEAMLINES.DESCRIPTION IS 'Label=Description'
   COMMENT ON COLUMN BEAMLINES.OPERATIVE IS 'Label=Operative'
   COMMENT ON COLUMN BEAMLINES.REF_NATION IS 'Label=Beamline owner country,List=SELECT code, name FROM countries ORDER BY NAME'
--------------------------------------------------------

CREATE TABLE BEAMLINES_REQUIRED 
   (	ID NUMBER NOT NULL ENABLE, 
	PROP_ID NUMBER NOT NULL ENABLE, 
	BML_NAME VARCHAR2(25) NOT NULL ENABLE, 
	 CONSTRAINT BLREQ_PK PRIMARY KEY (ID)
    
	 CONSTRAINT BEAMLINES_REQUIRED_BEAMLI_FK1 FOREIGN KEY (BML_NAME)
	  REFERENCES BEAMLINES (NAME) ENABLE, 
	 CONSTRAINT BLREQ_PROP_FK FOREIGN KEY (PROP_ID)
	  REFERENCES PROPOSALS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE BEAMLINE_METHOD 
   (	METHOD_ID NUMBER NOT NULL ENABLE, 
	BML_NAME VARCHAR2(25) NOT NULL ENABLE, 
	 CONSTRAINT PK_BEAMLINE_METHOD_1 PRIMARY KEY (METHOD_ID, BML_NAME)
    
	 CONSTRAINT FK_BEAMLINE_METHOD_MID FOREIGN KEY (METHOD_ID)
	  REFERENCES BEAMLINE_METHOD_TYPE (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE BEAMLINE_METHOD_CAT 
   (	ID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(200), 
	 UNIQUE (ID)
);
--------------------------------------------------------

CREATE TABLE BEAMLINE_METHOD_TYPE 
   (	ID NUMBER NOT NULL ENABLE, 
	CAT_ID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(200), 
	 UNIQUE (ID)
    
	 CONSTRAINT FK_BML_METHOD_CAT_ID FOREIGN KEY (CAT_ID)
	  REFERENCES BEAMLINE_METHOD_CAT (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE BT_DISTRIBUTION -- Description = Beamtime distribution
   (	SEMESTER NUMBER, 
	BML_SHORT_NAME VARCHAR2(10), 
	TOTAL_AVAIL NUMBER, 
	BML_ALLOCATED NUMBER, 
	IN_HOUSE NUMBER, 
	MAJOR_MAINT NUMBER, 
	ILO NUMBER, 
	GU_LT NUMBER, 
	NU_LT NUMBER, 
	AVAIL_LT NUMBER, 
	REQUESTED_LT NUMBER, 
	AVAIL_GU NUMBER, 
	PROPOSALS_GU NUMBER, 
	REQUESTED_GU NUMBER, 
	AVAIL_NU NUMBER, 
	PROPOSALS_NU NUMBER, 
	REQUESTED_NU NUMBER, 
	GU_RATIO NUMBER, 
	NU_RATIO NUMBER, 
	TOTAL_RATIO NUMBER, 
	AVAIL_FB NUMBER, 
	GU_ALREADY_ALLOCATED NUMBER, 
	NU_ALREADY_ALLOCATED NUMBER, 
	 CONSTRAINT BT_DISTRIBUTION_BEAMLINES_FK1 FOREIGN KEY (BML_SHORT_NAME)
	  REFERENCES BEAMLINES (SHORT_NAME) ENABLE
);
--------------------------------------------------------

CREATE TABLE COMMITTEES 
   (	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(30) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(256), 
	CMT_REF_ID VARCHAR2(5), 
	CMT_TYPE VARCHAR2(2), 
	STATUS VARCHAR2(1), 
	FACILITY VARCHAR2(1), 
	 PRIMARY KEY (ID)
    
	 CONSTRAINT COMMITTEES_NAME_UK UNIQUE (NAME)
    
	 CONSTRAINT COMMITTEES_CMT_REF_FK FOREIGN KEY (CMT_REF_ID)
	  REFERENCES COMMITTEES (NAME) ENABLE, 
	 CONSTRAINT COMMITTEES_FAC_FK FOREIGN KEY (FACILITY)
	  REFERENCES FACILITIES (CODE) ENABLE
);
   COMMENT ON COLUMN COMMITTEES.ID IS 'Sequence=SEQ_COMMITTEES_ID,Label=Committee ID'
   COMMENT ON COLUMN COMMITTEES.NAME IS 'Label=Committee Name'
   COMMENT ON COLUMN COMMITTEES.DESCRIPTION IS 'Label=Committee Description'
--------------------------------------------------------

CREATE TABLE COMMITTEE_BEAMLINES 
   (	ID NUMBER NOT NULL ENABLE, 
	BML_NAME VARCHAR2(20) NOT NULL ENABLE, 
	CMT_ID NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY (ID)
    
	 FOREIGN KEY (CMT_ID)
	  REFERENCES COMMITTEES (ID) ENABLE, 
	 FOREIGN KEY (BML_NAME)
	  REFERENCES BEAMLINES (NAME) ENABLE
);
   COMMENT ON COLUMN COMMITTEE_BEAMLINES.ID IS 'Sequence=SEQ_COMMITTEES_ID,Label=ID'
   COMMENT ON COLUMN COMMITTEE_BEAMLINES.BML_NAME IS 'Label=Beamline Name,List=SELECT NAME FROM BEAMLINES'
--------------------------------------------------------

CREATE TABLE COMPETENCE 
   (	CODE VARCHAR2(2) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(40), 
	PRIO NUMBER NOT NULL ENABLE, 
	 CONSTRAINT COMPETENCE_UK1 UNIQUE (PRIO)
	 CONSTRAINT COMPETENCE_PK PRIMARY KEY (CODE)
);
--------------------------------------------------------

CREATE TABLE COMUNI_ITALIANI 
   (	NOME VARCHAR2(40), 
	PROVINCIA VARCHAR2(2), 
	REGIONE VARCHAR2(3), 
	CAP NUMBER, 
	PREFISSO VARCHAR2(4), 
	COD_COMUNE VARCHAR2(5) NOT NULL ENABLE, 
	COD_ISTAT NUMBER
);
--------------------------------------------------------

CREATE TABLE COUNTRIES 
   (	NAME VARCHAR2(50) NOT NULL ENABLE, 
	CODE VARCHAR2(4) NOT NULL ENABLE, 
	EU VARCHAR2(1), 
	IBAN_LEN NUMBER, 
	CONT_CODE VARCHAR2(2), 
	ACCOUNT_POSITION NUMBER, 
	ACCOUNT_LENGTH NUMBER, 
	CERIC VARCHAR2(1), 
	 CONSTRAINT CNT_PK PRIMARY KEY (CODE, NAME)
);
   COMMENT ON COLUMN COUNTRIES.NAME IS 'Label=Country'
--------------------------------------------------------

CREATE TABLE DATES_RANGES 
   (	ID NUMBER NOT NULL ENABLE, 
	DTRANGE_BEGIN DATE NOT NULL ENABLE, 
	DTRANGE_END DATE NOT NULL ENABLE, 
	ACCEPTABLE VARCHAR2(240) NOT NULL ENABLE, 
	PROP_ID NUMBER NOT NULL ENABLE, 
	 CONSTRAINT AVCON_DATES_ACCEP_000 CHECK (ACCEPTABLE IN ('Y','N')) ENABLE, 
	 CONSTRAINT DTRANGE_PK PRIMARY KEY (ID)
    
	 CONSTRAINT DTRANGE_PROP_FK FOREIGN KEY (PROP_ID)
	  REFERENCES PROPOSALS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE DOCUMENTS 
   (	ID NUMBER NOT NULL ENABLE, 
	OID NUMBER, 
	PROP_ID NUMBER, 
	DESCRIPTION VARCHAR2(255), 
	 CONSTRAINT SYS_C0048211 UNIQUE (ID)
    
	 CONSTRAINT SYS_C0048890 FOREIGN KEY (PROP_ID)
	  REFERENCES PROPOSALS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE ELEARN_COURSE 
   (	ID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(2000) NOT NULL ENABLE, 
	PRIO NUMBER, 
	DATE_START DATE, 
	DATE_END DATE, 
	OBL_TYPE VARCHAR2(3), 
	LEARN_MODE VARCHAR2(2), 
	TEACHER_ID NUMBER, 
	COMPANY_ID NUMBER, 
	OBJECTIVES VARCHAR2(2000), 
	CONTENTS VARCHAR2(2000), 
	INITIATIVE_ID NUMBER, 
	COST NUMBER, 
	HOURS NUMBER, 
	HVFO_CODE VARCHAR2(20), 
	TRAINING_TYPE VARCHAR2(2), 
	FINANCED_EXT VARCHAR2(1), 
	LEARNERS_STUD NUMBER, 
	LEARNERS_OTHR NUMBER, 
	INSTITUTE_ID NUMBER, 
	NOTES VARCHAR2(2000), 
	 CONSTRAINT ELEARN_COURSE_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE ELEARN_COURSE_DOWNLOADS 
   (	ID NUMBER NOT NULL ENABLE, 
	COURSE_ID NUMBER NOT NULL ENABLE, 
	DOC_ID NUMBER, 
	USR_ID NUMBER, 
	DOWNLOAD_DATE DATE, 
	 CONSTRAINT ELEARN_COURSE_DOWNLOADS_PK PRIMARY KEY (ID)
    
	 CONSTRAINT ELEARN_COURSE_DOWNLOADS_E_FK1 FOREIGN KEY (COURSE_ID)
	  REFERENCES ELEARN_COURSE (ID) ENABLE, 
	 CONSTRAINT ELEARN_COURSE_DOWNLOADS_U_FK1 FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE ELEARN_TESTS 
   (	ID NUMBER NOT NULL ENABLE, 
	COURSE_ID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(2000) NOT NULL ENABLE, 
	MAX_ERRORS NUMBER NOT NULL ENABLE, 
	PRIO NUMBER NOT NULL ENABLE, 
	 CONSTRAINT ELEARN_TESTS_PK PRIMARY KEY (ID)
    
	 CONSTRAINT ELEARN_TESTS_ELEARN_COURS_FK1 FOREIGN KEY (COURSE_ID)
	  REFERENCES ELEARN_COURSE (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE ELEARN_TEST_ATTEMPTS 
   (	ID NUMBER NOT NULL ENABLE, 
	TEST_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	FROM_IP VARCHAR2(200) NOT NULL ENABLE, 
	SUBMISSION DATE NOT NULL ENABLE, 
	RIGHT NUMBER NOT NULL ENABLE, 
	TOTAL NUMBER NOT NULL ENABLE, 
	PASSED VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT ELEARN_TEST_ATTEMPTS_PK PRIMARY KEY (ID)
    
	 CONSTRAINT ELEARN_TEST_ATTEMPTS_ELEA_FK1 FOREIGN KEY (TEST_ID)
	  REFERENCES ELEARN_TESTS (ID) ENABLE, 
	 CONSTRAINT ELEARN_TEST_ATTEMPTS_USER_FK1 FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE EMAIL_QUEUE 
   (	CCADDR VARCHAR2(500), 
	ID NUMBER NOT NULL ENABLE, 
	MSG CLOB, 
	RESULT VARCHAR2(300), 
	SENDER VARCHAR2(300), 
	SEND_DATE DATE, 
	SENT_DATE DATE, 
	SUBJ VARCHAR2(300), 
	TOADDR VARCHAR2(2000), 
	USR_ID NUMBER, 
	RETURN_RECEIPT VARCHAR2(1), 
	PRIO VARCHAR2(1), 
	BCCADDR VARCHAR2(500), 
	 CONSTRAINT PK_EMAIL_QUEUE PRIMARY KEY (ID)
    
	 CONSTRAINT FK_EMAIL_QUEUE_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE ENABLINGS 
   (	ID NUMBER NOT NULL ENABLE, 
	OBJECT_ID NUMBER NOT NULL ENABLE, 
	ENBT_ID NUMBER NOT NULL ENABLE, 
	RLT_ID NUMBER NOT NULL ENABLE, 
	 CONSTRAINT ENB_PK PRIMARY KEY (ID)
    
	 CONSTRAINT ENB_ENBT_FK FOREIGN KEY (ENBT_ID)
	  REFERENCES ENABLING_TYPES (ID) ENABLE, 
	 CONSTRAINT ENB_RLT_FK FOREIGN KEY (RLT_ID)
	  REFERENCES ROLE_TYPES (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE ENABLING_TYPES 
   (	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(32) NOT NULL ENABLE, 
	 CONSTRAINT ENBT_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE ESTR_ALOHA 
   (	ALOHA_ID NUMBER NOT NULL ENABLE, 
	LANGUAGE VARCHAR2(50), 
	LANG_ID NUMBER, 
	ALOHA VARCHAR2(500), 
	 UNIQUE (ALOHA_ID)
);
--------------------------------------------------------

CREATE TABLE EU_FINANCIAL_SUPPORT 
   (	USR_ID NUMBER NOT NULL ENABLE, 
	ACCESS_ID NUMBER NOT NULL ENABLE, 
	BANKING_ID NUMBER NOT NULL ENABLE, 
	PASSPORT_ID NUMBER NOT NULL ENABLE, 
	ESTIMATE_COST NUMBER, 
	NOTES CLOB, 
	TRANSPORTATION VARCHAR2(10), 
	ROOM_HOTEL VARCHAR2(4), 
	 CONSTRAINT UNIQUE_USR_ID_PROP_ID UNIQUE (USR_ID, ACCESS_ID)
    
	 CONSTRAINT FK_EU_FINANCIAL_SUPPORT_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE EVALUATIONS -- Description: Proposals evaluation
   (	ID NUMBER NOT NULL ENABLE, 
	SCORE NUMBER(38,0), 
	COMMENTS CLOB, 
	PROP_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	EVLT_ID NUMBER NOT NULL ENABLE, 
	RELEVANCE NUMBER, 
	ORIGINALITY NUMBER, 
	LOWRISK NUMBER, 
	NEEDELETTRA NUMBER, 
	PREVRECORD NUMBER, 
	TECHNICAL_EVLT VARCHAR2(1), 
	BML_OR_CMT VARCHAR2(25), 
	REALSHIFTS NUMBER, 
	STATUS VARCHAR2(1), 
	FINAL_SCORE NUMBER(4,2), 
	WEIGHTEDAVERAGE NUMBER(4,2), 
	COMPETENCE NUMBER(4,0), 
	QUARTER VARCHAR2(10), 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ELECTRON_BEAM VARCHAR2(1), 
	INTERNAL_COMMENTS CLOB, 
	REEDITING VARCHAR2(1), 
	REEDIT_COMMENTS CLOB, 
	 CONSTRAINT EVAL_UNIQUE UNIQUE (PROP_ID, USR_ID, EVLT_ID, BML_OR_CMT)
    
	 CONSTRAINT EVAL_PK PRIMARY KEY (ID)
    
	 CONSTRAINT EVAL_EVLT_FK FOREIGN KEY (EVLT_ID)
	  REFERENCES EVALUATION_TYPES (ID) ENABLE, 
	 CONSTRAINT EVAL_PROP_FK FOREIGN KEY (PROP_ID)
	  REFERENCES PROPOSALS (ID) ENABLE, 
	 CONSTRAINT EVAL_USR_FK FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE EVALUATIONS_ASSIGNMENTS 
   (	PROP_ID NUMBER NOT NULL ENABLE, 
	EVALUATOR_ID NUMBER NOT NULL ENABLE, 
	BML_OR_CMT VARCHAR2(25), 
	EMAILED VARCHAR2(1), 
	 CONSTRAINT EVALUATIONS_ASSIGNMENTS_UK1 UNIQUE (PROP_ID, EVALUATOR_ID, BML_OR_CMT)
	 CONSTRAINT FK_EVAL_ASSIGN_EVALUATOR_ID FOREIGN KEY (EVALUATOR_ID)
	  REFERENCES USERS (ID) ENABLE, 
	 CONSTRAINT FK_EVAL_ASSIGN_PROP_ID FOREIGN KEY (PROP_ID)
	  REFERENCES PROPOSALS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE EVALUATIONS_AUG_17_2020 -- Description: Backup
   (	ID NUMBER NOT NULL ENABLE, 
	SCORE NUMBER(38,0), 
	COMMENTS CLOB, 
	PROP_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	EVLT_ID NUMBER NOT NULL ENABLE, 
	RELEVANCE NUMBER, 
	ORIGINALITY NUMBER, 
	LOWRISK NUMBER, 
	NEEDELETTRA NUMBER, 
	PREVRECORD NUMBER, 
	TECHNICAL_EVLT VARCHAR2(1), 
	BML_OR_CMT VARCHAR2(25), 
	REALSHIFTS NUMBER, 
	STATUS VARCHAR2(1), 
	FINAL_SCORE NUMBER(4,2), 
	WEIGHTEDAVERAGE NUMBER(4,2), 
	COMPETENCE NUMBER(4,0), 
	QUARTER VARCHAR2(10), 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ELECTRON_BEAM VARCHAR2(1), 
	INTERNAL_COMMENTS CLOB, 
	REEDITING VARCHAR2(1), 
	REEDIT_COMMENTS CLOB
);
--------------------------------------------------------

CREATE TABLE EVALUATIONS_LOG 
   (	ID NUMBER, 
	PROP_ID NUMBER, 
	USER_ID NUMBER, 
	EVENT_DATE DATE, 
	EVALUATION_TYPE NUMBER, 
	BML_OR_CMT VARCHAR2(25)
);
--------------------------------------------------------

CREATE TABLE EVALUATIONS_SCIENTIFIC 
   (	ID VARCHAR2(200), 
	PROP_ID NUMBER, 
	PROPOSER VARCHAR2(100), 
	TITLE VARCHAR2(300), 
	EVALUATOR VARCHAR2(100), 
	ASSIGNED_SHIFTS VARCHAR2(10), 
	SCORE VARCHAR2(10), 
	COMMENTS VARCHAR2(4000)
);
--------------------------------------------------------

CREATE TABLE EVALUATION_TYPES 
   (	ID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT EVLT_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE EVENTS 
   (	ID NUMBER NOT NULL ENABLE, 
	EVT_BEGIN DATE NOT NULL ENABLE, 
	EVT_END DATE NOT NULL ENABLE, 
	ETP_ID NUMBER NOT NULL ENABLE, 
	FACILITY VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT EVT_PK PRIMARY KEY (ID)
    
	 CONSTRAINT EVT_ETP_FK FOREIGN KEY (ETP_ID)
	  REFERENCES EVENT_TYPES (ID) ENABLE, 
	 CONSTRAINT FK_EVENTS_FACILITY FOREIGN KEY (FACILITY)
	  REFERENCES FACILITIES (CODE) ENABLE
);
--------------------------------------------------------

CREATE TABLE EVENT_PARAMETERS 
   (	ID NUMBER NOT NULL ENABLE, 
	VALUE VARCHAR2(100) NOT NULL ENABLE, 
	EVT_ID NUMBER NOT NULL ENABLE, 
	EPT_ID NUMBER NOT NULL ENABLE, 
	 CONSTRAINT EPAR_PK PRIMARY KEY (ID)
    
	 CONSTRAINT EPAR_EPT_FK FOREIGN KEY (EPT_ID)
	  REFERENCES EVENT_PARAMETER_TYPES (ID) ENABLE, 
	 CONSTRAINT EPAR_EVT_FK FOREIGN KEY (EVT_ID)
	  REFERENCES EVENTS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE EVENT_PARAMETER_TYPES 
   (	EVENT_TYPE_ID NUMBER NOT NULL ENABLE, 
	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(30) NOT NULL ENABLE, 
	EPT_VIEW VARCHAR2(2048), 
	 CONSTRAINT EPT_PK PRIMARY KEY (ID)
    
	 CONSTRAINT EPT_ETP_FK FOREIGN KEY (EVENT_TYPE_ID)
	  REFERENCES EVENT_TYPES (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE EVENT_TYPES 
   (	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(50) NOT NULL ENABLE, 
	FAMILY_ID NUMBER, 
	 CONSTRAINT ETP_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE FACILITIES 
   (	CODE VARCHAR2(1) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(100) NOT NULL ENABLE, 
	FIRST_PROP_ID NUMBER NOT NULL ENABLE, 
	PRIO NUMBER, 
	 CONSTRAINT PK_CODE PRIMARY KEY (CODE)
);
--------------------------------------------------------

CREATE TABLE FEEDBACKS 
   (	FBKT_ID NUMBER NOT NULL ENABLE, 
	SMR_ID NUMBER NOT NULL ENABLE, 
	ID NUMBER NOT NULL ENABLE, 
	SCORE VARCHAR2(1), 
	FBK_COMMENT VARCHAR2(2048), 
	 CONSTRAINT FBK_PK PRIMARY KEY (ID)
    
	 CONSTRAINT FBK_FBKT_FK FOREIGN KEY (FBKT_ID)
	  REFERENCES FEEDBACK_TYPES (ID) ENABLE, 
	 CONSTRAINT FBK_SMR_FK FOREIGN KEY (SMR_ID)
	  REFERENCES SUMMARIES (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE FEEDBACK_PARTICIPANTS 
   (	ID NUMBER NOT NULL ENABLE, 
	FBK_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	 CHECK (USR_ID IS NOT NULL) ENABLE, 
	 CHECK (FBK_ID IS NOT NULL) ENABLE, 
	 CHECK (ID IS NOT NULL) ENABLE, 
	 PRIMARY KEY (ID)
    
	 FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE, 
	 FOREIGN KEY (FBK_ID)
	  REFERENCES SUMMARIES (ID) ENABLE
);
   COMMENT ON COLUMN FEEDBACK_PARTICIPANTS.ID IS 'Sequence=SEQ_FEEDBACK_PARTICIPANTS_ID,Label=Participant ID'
   COMMENT ON COLUMN FEEDBACK_PARTICIPANTS.USR_ID IS 'Label=Participant'
--------------------------------------------------------

CREATE TABLE FEEDBACK_TYPES 
   (	ID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(128) NOT NULL ENABLE, 
	NEEDSCORE VARCHAR2(1) NOT NULL ENABLE, 
	VERSION NUMBER, 
	SHOW_ORDER NUMBER, 
	 CONSTRAINT FBKT_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE HOLIDAYS 
   (	WHEN DATE, 
	DESCRIPTION VARCHAR2(100), 
	HOL_TYPE VARCHAR2(4)
);
--------------------------------------------------------

CREATE TABLE HOME_LINKS 
   (	SECTION VARCHAR2(32) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(250) NOT NULL ENABLE, 
	URL VARCHAR2(200), 
	PRIO NUMBER NOT NULL ENABLE, 
	VALID_FUNCTION VARCHAR2(200), 
	 CONSTRAINT HOME_LINKS_PK PRIMARY KEY (SECTION, PRIO)
    
	 CONSTRAINT HOME_LINKS_HOME_SECTIONS_FK1 FOREIGN KEY (SECTION)
	  REFERENCES HOME_SECTIONS (NAME) ENABLE
);
--------------------------------------------------------

CREATE TABLE HOME_PANES 
   (	NAME VARCHAR2(50) NOT NULL ENABLE, 
	SECTION_NAME VARCHAR2(32) NOT NULL ENABLE, 
	SECTION_BIN CHAR(1) NOT NULL ENABLE, 
	SECTION_PRIO NUMBER NOT NULL ENABLE, 
	TAB_NAME VARCHAR2(50), 
	 CONSTRAINT HOME_PAGES_PK PRIMARY KEY (NAME, SECTION_NAME, SECTION_BIN, SECTION_PRIO)
);
--------------------------------------------------------

CREATE TABLE HOME_SECTIONS 
   (	NAME VARCHAR2(32) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(200) NOT NULL ENABLE, 
	VALID_FUNCTION VARCHAR2(200), 
	 CONSTRAINT HOME_SECTIONS_PK PRIMARY KEY (NAME)
);
--------------------------------------------------------

CREATE TABLE HOME_TABS 
   (	NAME VARCHAR2(50), 
	PANE_NAME VARCHAR2(50), 
	ORDERING CHAR(1), 
	LOGO_HREF VARCHAR2(1000)
);
--------------------------------------------------------

CREATE TABLE HTML_ENTITIES 
   (	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(20), 
	DESCRIPTION VARCHAR2(100), 
	SUBSTITUTION VARCHAR2(20)
);
--------------------------------------------------------

CREATE TABLE INFOS 
   (	ID NUMBER, 
	LANGUAGE VARCHAR2(15) NOT NULL ENABLE, 
	LABEL VARCHAR2(80) NOT NULL ENABLE, 
	URL VARCHAR2(250) NOT NULL ENABLE, 
	FACILITY VARCHAR2(1), 
	 CONSTRAINT PK_INFOS PRIMARY KEY (ID)
);
   COMMENT ON COLUMN INFOS.ID IS 'Sequence=SEQ_INFOS_ID,Label=Infos ID'
   COMMENT ON COLUMN INFOS.LANGUAGE IS 'Label=Language,DefList=English,Italian'
   COMMENT ON COLUMN INFOS.LABEL IS 'Label=Label'
   COMMENT ON COLUMN INFOS.URL IS 'Label=Url,Default=http://'
--------------------------------------------------------

CREATE TABLE INSTITUTES 
   (	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(255) NOT NULL ENABLE, 
	ADDRESS VARCHAR2(160) NOT NULL ENABLE, 
	CNT_NAME VARCHAR2(50) NOT NULL ENABLE, 
	CITY VARCHAR2(40), 
	ZIP VARCHAR2(20) NOT NULL ENABLE, 
	INS_TYPE VARCHAR2(3), 
	MODIF_USR_ID NUMBER, 
	MODIF_DATE DATE, 
	STATE_PROV VARCHAR2(40), 
	ITALIAN_PROV VARCHAR2(2), 
	ITALIAN_CITY VARCHAR2(40), 
	END_DATE DATE, 
	PEC VARCHAR2(60), 
	NOTES VARCHAR2(2000), 
	EMAIL VARCHAR2(60), 
	 CONSTRAINT INS_PK PRIMARY KEY (ID)
);
   COMMENT ON COLUMN INSTITUTES.ID IS 'Sequence=SEQ_USERS_ID,Label=Institute'
   COMMENT ON COLUMN INSTITUTES.NAME IS 'Label=Institute name'
   COMMENT ON COLUMN INSTITUTES.ADDRESS IS 'Label=Address'
   COMMENT ON COLUMN INSTITUTES.CNT_NAME IS 'Label=Country,List=SELECT NAME AS A FROM COUNTRIES'
   COMMENT ON COLUMN INSTITUTES.CITY IS 'Label=City'
   COMMENT ON COLUMN INSTITUTES.ZIP IS 'Label=Zip code'
   COMMENT ON COLUMN INSTITUTES.INS_TYPE IS 'Label=Institute Type, List=select code, description from list_of_values where list = ''InstituteType'''
    
--------------------------------------------------------

CREATE TABLE INSTITUTES_BCK -- Description: Backup
   (	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(255) NOT NULL ENABLE, 
	ADDRESS VARCHAR2(160) NOT NULL ENABLE, 
	CNT_NAME VARCHAR2(50) NOT NULL ENABLE, 
	CITY VARCHAR2(40), 
	ZIP VARCHAR2(20) NOT NULL ENABLE, 
	INS_TYPE VARCHAR2(3), 
	MODIF_USR_ID NUMBER, 
	MODIF_DATE DATE, 
	STATE_PROV VARCHAR2(40), 
	ITALIAN_PROV VARCHAR2(2), 
	ITALIAN_CITY VARCHAR2(40), 
	END_DATE DATE, 
	PEC VARCHAR2(60), 
	NOTES VARCHAR2(2000), 
	EMAIL VARCHAR2(60)
);
--------------------------------------------------------

CREATE TABLE KEY_BUILDINGS 
   (	ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(20) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(1024), 
	 CONSTRAINT KEY_BUILDINGS_UK1 UNIQUE (TITLE)
    
	 CONSTRAINT KEY_BUILDINGS_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE KEY_FLOORS 
   (	ID NUMBER NOT NULL ENABLE, 
	BUILDING_ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(20) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(1024), 
	 CONSTRAINT KEY_FLOORS_UK1 UNIQUE (BUILDING_ID, TITLE)
    
	 CONSTRAINT KEY_FLOORS_PK PRIMARY KEY (ID)
    
	 CONSTRAINT KEY_FLOORS_FK1 FOREIGN KEY (BUILDING_ID)
	  REFERENCES KEY_BUILDINGS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE KEY_PHONES 
   (	ID NUMBER NOT NULL ENABLE, 
	ROOM_ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(50) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(1024), 
	 CONSTRAINT KEY_PHONES_UK1 UNIQUE (TITLE)
    
	 CONSTRAINT KEY_PHONES_PK PRIMARY KEY (ID)
    
	 CONSTRAINT KEY_PHONES_FK1 FOREIGN KEY (ROOM_ID)
	  REFERENCES KEY_ROOMS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE KEY_ROOMS 
   (	ID NUMBER NOT NULL ENABLE, 
	FLOOR_ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(50) NOT NULL ENABLE, 
	OTHER_NAME VARCHAR2(64), 
	DESCRIPTION VARCHAR2(1024), 
	 CONSTRAINT KEY_ROOMS_UK1 UNIQUE (FLOOR_ID, TITLE)
    
	 CONSTRAINT KEY_ROOMS_PK PRIMARY KEY (ID)
    
	 CONSTRAINT KEY_ROOMS_FK1 FOREIGN KEY (FLOOR_ID)
	  REFERENCES KEY_FLOORS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE LIGHTSOURCES 
   (	ID NUMBER, 
	NAME VARCHAR2(40), 
	TOWN VARCHAR2(50), 
	CITY VARCHAR2(50), 
	ADDRESS VARCHAR2(100), 
	ZIP VARCHAR2(10), 
	COUNTRY_CODE VARCHAR2(2), 
	HOMEPAGE VARCHAR2(500), 
	LOCATION VARCHAR2(200)
);
--------------------------------------------------------

CREATE TABLE LIST_OF_VALUES 
   (	LIST VARCHAR2(40), 
	CODE VARCHAR2(100), 
	DESCRIPTION VARCHAR2(100), 
	ID NUMBER
);
--------------------------------------------------------

CREATE TABLE LOG_EXCEPTIONS 
   (	ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	REAL_USR_ID NUMBER, 
	ACT_WHEN DATE NOT NULL ENABLE, 
	ACT_WHERE VARCHAR2(255) NOT NULL ENABLE, 
	FORMAT_ERROR_STACK VARCHAR2(2000), 
	FORMAT_ERROR_BACKTRACE VARCHAR2(4000), 
	CGI_ENV CLOB, 
	 CONSTRAINT LOG_EXCEPTION_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE MATRICULAS 
   (	USR_ID NUMBER NOT NULL ENABLE, 
	MATRICULA VARCHAR2(5) NOT NULL ENABLE, 
	 CONSTRAINT PK_MATRICULAS PRIMARY KEY (MATRICULA)
    
	 CONSTRAINT FK_MATRICULAS_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE OFFICES 
   (	DESCRIPTION VARCHAR2(100), 
	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(10), 
	DISABLED VARCHAR2(1), 
	 CONSTRAINT ID PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE OWA_DOC_DOCUMENTS 
   (	ID NUMBER NOT NULL ENABLE, 
	DOC BLOB, 
	DOC_DATE DATE
);
--------------------------------------------------------

CREATE TABLE PARAMETER 
   (	ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	VALUE VARCHAR2(255), 
	RLT_ID NUMBER, 
	PARMTY_ID NUMBER NOT NULL ENABLE, 
	 CONSTRAINT PARAM_PK PRIMARY KEY (ID)
    
	 CONSTRAINT PARAM_PARMTY_FK FOREIGN KEY (PARMTY_ID)
	  REFERENCES PARAMS_TYPES (ID) ENABLE
);
   COMMENT ON COLUMN PARAMETER.ID IS 'Sequence=SEQ_PARAMETERS_ID,Label=ID'
   COMMENT ON COLUMN PARAMETER.VALUE IS 'Label=Value'
   COMMENT ON COLUMN PARAMETER.RLT_ID IS 'Label=Role,List=SELECT ID, DESCRIPTION FROM ROLE_TYPES order by description'
   COMMENT ON COLUMN PARAMETER.PARMTY_ID IS 'Label=Parameter Type,List=SELECT ID,NAME FROM PARAMS_TYPES'
--------------------------------------------------------

CREATE TABLE PARAMS_TYPES 
   (	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(40) NOT NULL ENABLE, 
	PARMTY_COMMENT VARCHAR2(1024), 
	 CONSTRAINT PARMTY_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE PARTICIPANTS 
   (	ID NUMBER NOT NULL ENABLE, 
	PROP_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER, 
	NAME VARCHAR2(40), 
	INSTITUTE_NAME VARCHAR2(255), 
	ADDRESS VARCHAR2(255), 
	INS_ID NUMBER, 
	 CONSTRAINT PARTICIPANTS_UK1 UNIQUE (PROP_ID, USR_ID, NAME)
    
	 CONSTRAINT PART_PK PRIMARY KEY (ID)
    
	 CONSTRAINT PARTICIPANTS_INSTITUTES_FK1 FOREIGN KEY (INS_ID)
	  REFERENCES INSTITUTES (ID) ENABLE, 
	 CONSTRAINT PART_PROP_FK FOREIGN KEY (PROP_ID)
	  REFERENCES PROPOSALS (ID) ENABLE, 
	 CONSTRAINT PART_USR_FK FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) DISABLE
);
--------------------------------------------------------

CREATE TABLE PASSPORTS 
   (	USR_ID NUMBER, 
	PASSPORT_ID NUMBER, 
	NATIONALITY VARCHAR2(2), 
	PASS_NUMBER VARCHAR2(15), 
	ISSUE_DATE DATE, 
	EXPIRATION_DATE DATE, 
	ISSUED_AT VARCHAR2(30), 
	DOC_TYPE VARCHAR2(2), 
	 CONSTRAINT FK_PASSPORTS_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE PERMISSIONS 
   (	ID NUMBER NOT NULL ENABLE, 
	PERM_GRANT VARCHAR2(80) NOT NULL ENABLE, 
	RLT_ID NUMBER NOT NULL ENABLE, 
	 CONSTRAINT PERM_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE PROPOSALS
   (	ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(255) NOT NULL ENABLE, 
	USER_CATEGORY VARCHAR2(1) NOT NULL ENABLE, 
	RESEARCH_CATEGORY VARCHAR2(1), 
	EU_SUPPORT VARCHAR2(1) NOT NULL ENABLE, -- EU_support: Y = Yes, N = No
	PHYSICS VARCHAR2(1) NOT NULL ENABLE, -- physics: Y = Yes, N = No
	CHEMISTRY VARCHAR2(1) NOT NULL ENABLE, -- chemistry: Y = Yes, N = No
	MEDICAL VARCHAR2(1) NOT NULL ENABLE, -- medical: Y = Yes, N = No
	LIFE_SCIENCES VARCHAR2(1) NOT NULL ENABLE, -- life_sciences: Y = Yes, N = No
	TECH_INSTRUMENTATION VARCHAR2(1) NOT NULL ENABLE, -- tech_instrumentation: Y = Yes, N = No
	OTHER VARCHAR2(50), 
	SHIFTS NUMBER(38,0) NOT NULL ENABLE, 
	ELECTRON_BEAM VARCHAR2(1), 
	PROPOSAL_CATEGORY VARCHAR2(1) NOT NULL ENABLE, -- proposal_category: C = Continuation, R = Resubmission, N = New
	APPLICATION_CATEGORY VARCHAR2(1), -- application_category: N =  Normal,  U = Urgent, L = Long Term
	ENERGY VARCHAR2(255), 
	RESOLUTION VARCHAR2(80), 
	OTHER_REQUIREMENTS VARCHAR2(255), 
	SAMPLE_TREATMENT VARCHAR2(400), 
	AVAILABLE_EQUIPMENT VARCHAR2(400), 
	ADDITIONAL_EQUIPMENT VARCHAR2(255), 
	OFFLINE_FACILITIES VARCHAR2(255), 
	STATUS VARCHAR2(1) NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	LOCAL_CONTACT_ID NUMBER, 
	SUBMISSION_DATE DATE, 
	BML_NAME VARCHAR2(25), 
	PROP_SUBMISSION_DATE DATE, 
	PREVIOUS_PROPCODE VARCHAR2(32), 
	EU_SUPPORTED VARCHAR2(1), 
	REALSHIFTS NUMBER, 
	DESCRIPTION CLOB, 
	CONTACT_NAME VARCHAR2(90), 
	EARTH_SCIENCES VARCHAR2(1), 
	MATERIALS_SCIENCE VARCHAR2(1), 
	PHYSICAL_CHEM VARCHAR2(1), 
	INDUSTRY_COLLABORATION VARCHAR2(1), 
	INS_ID NUMBER, 
	CMT_ID VARCHAR2(30), 
	RESEARCH_AREA VARCHAR2(3), 
	ICTP_SUPPORT VARCHAR2(1), 
	USR_LASTNAME VARCHAR2(40), 
	REQUIRED_BML_NAME VARCHAR2(25), 
	FEASIBILITY VARCHAR2(1), -- feasibility: Y = Viable, N = Unfeasible, U = Conflicting, R = Feasible on required beamline, A = Feasible on alternative beamline
	REQ_ALT_BML_NAME VARCHAR2(25), 
	BML_LOGICAL_OPERATOR VARCHAR2(3), 
	REQ_ELECTRON_BEAM VARCHAR2(1), 
	REQ_APPLICATION_CATEGORY VARCHAR2(1), 
	ALLOCATION_MAIL VARCHAR2(1) DEFAULT null, 
	DISCIPLINE VARCHAR2(2), 
	SUB_DISCIPLINE VARCHAR2(8), 
	ACHIEVEMENTS CLOB, 
	SEMESTER NUMBER, 
	EU_SUPPORT_CRUCIAL VARCHAR2(1), 
	AUTOSCHEDULING VARCHAR2(1), 
	AUTOSCHEDULE_COUNTER NUMBER, 
	LONGTERM_COMMENTS VARCHAR2(220), 
	EMAIL_ACHIEV_EXPREP DATE, 
	EU_REFUNDABLE_DAYS NUMBER, 
	MONTHLY VARCHAR2(1), 
	ICTP_SUPPORTED NUMBER, 
	FACILITY VARCHAR2(1), 
	POLARIZATION VARCHAR2(4), 
	TUNABILITY NUMBER, 
	SAMPLE_TEMPERATURE NUMBER, 
	LAST_MINUTE VARCHAR2(1), 
	BIOSTRUCTX_CODE VARCHAR2(10), 
	IAEA VARCHAR2(1), 
	WAYFORLIGHTS VARCHAR2(1), 
	FERMI_MODE NUMBER, 
	ASSIGNMENT_MAIL VARCHAR2(1), 
	LASERLAB_FUNDED VARCHAR2(1), 
	LASERLAB_REQUEST VARCHAR2(20), 
	CULTURAL_HERITAGE VARCHAR2(1), 
	LAST_CHANGE DATE, 
	FUND_SOURCE NUMBER(4,0), 
	NOTES CLOB, 
	 CONSTRAINT AVCON_PROPO_TECH__000 CHECK (TECH_INSTRUMENTATION IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_RESEA_000 CHECK (RESEARCH_CATEGORY IN ('P','N')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_PROPO_000 CHECK (PROPOSAL_CATEGORY IN ('C', 'R', 'N')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_PHYSI_000 CHECK (PHYSICS IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_PHCHE_000 CHECK (PHYSICAL_CHEM IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_MEDIC_000 CHECK (MEDICAL IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_MATER_000 CHECK (MATERIALS_SCIENCE IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_LIFE__000 CHECK (LIFE_SCIENCES IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_INDUS_000 CHECK (INDUSTRY_COLLABORATION IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_EU_SU_000 CHECK (EU_SUPPORT IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_ELECT_000 CHECK (ELECTRON_BEAM IN ('S','M','F')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_EARTH_000 CHECK (EARTH_SCIENCES IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_CHEMI_000 CHECK (CHEMISTRY IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_PROPO_APPLI_000 CHECK (APPLICATION_CATEGORY IN ('N','U','L')) ENABLE, 
	 CONSTRAINT PROP_PK PRIMARY KEY (ID)
    
	 CONSTRAINT FK_FACILITY FOREIGN KEY (FACILITY)
	  REFERENCES FACILITIES (CODE) ENABLE, 
	 CONSTRAINT PROPOSALS_BEAMLINES_FK1 FOREIGN KEY (REQUIRED_BML_NAME)
	  REFERENCES BEAMLINES (NAME) ENABLE, 
	 CONSTRAINT PROPOSALS_BEAMLINES_FK2 FOREIGN KEY (REQ_ALT_BML_NAME)
	  REFERENCES BEAMLINES (NAME) ENABLE, 
	 CONSTRAINT PROPOSALS_INSTITUTES_FK1 FOREIGN KEY (INS_ID)
	  REFERENCES INSTITUTES (ID) ENABLE, 
	 CONSTRAINT PROP_BML_FK FOREIGN KEY (BML_NAME)
	  REFERENCES BEAMLINES (NAME) ENABLE, 
	 CONSTRAINT PROP_USR_CONCTACT_IS_FK FOREIGN KEY (LOCAL_CONTACT_ID)
	  REFERENCES USERS (ID) ENABLE, 
	 CONSTRAINT PROP_USR_FK FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
	COMMENT ON COLUMN PROPOSALS.STATUS IS 'Label = Status, List= Select code, name from proposals_stataus'
	COMMENT ON COLUMN PROPOSALS.DISCIPLINE IS 'Label=Discipline ,List=SELECT code, description FROM competence ORDER BY prio'
	COMMENT ON COLUMN PROPOSALS.SUB_DISCIPLINE IS 'Label=Sub Discipline ,List=SELECT code, description FROM sub_competence'
--------------------------------------------------------

CREATE TABLE PROPOSALS_AUG_17_2020 --Back-up for proposals
   (	ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(255) NOT NULL ENABLE, 
	USER_CATEGORY VARCHAR2(1) NOT NULL ENABLE, 
	RESEARCH_CATEGORY VARCHAR2(1), 
	EU_SUPPORT VARCHAR2(1) NOT NULL ENABLE, 
	PHYSICS VARCHAR2(1) NOT NULL ENABLE, 
	CHEMISTRY VARCHAR2(1) NOT NULL ENABLE, 
	MEDICAL VARCHAR2(1) NOT NULL ENABLE, 
	LIFE_SCIENCES VARCHAR2(1) NOT NULL ENABLE, 
	TECH_INSTRUMENTATION VARCHAR2(1) NOT NULL ENABLE, 
	OTHER VARCHAR2(50), 
	SHIFTS NUMBER(38,0) NOT NULL ENABLE, 
	ELECTRON_BEAM VARCHAR2(1), 
	PROPOSAL_CATEGORY VARCHAR2(1) NOT NULL ENABLE, 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ENERGY VARCHAR2(255), 
	RESOLUTION VARCHAR2(80), 
	OTHER_REQUIREMENTS VARCHAR2(255), 
	SAMPLE_TREATMENT VARCHAR2(400), 
	AVAILABLE_EQUIPMENT VARCHAR2(400), 
	ADDITIONAL_EQUIPMENT VARCHAR2(255), 
	OFFLINE_FACILITIES VARCHAR2(255), 
	STATUS VARCHAR2(1) NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	LOCAL_CONTACT_ID NUMBER, 
	SUBMISSION_DATE DATE, 
	BML_NAME VARCHAR2(25), 
	PROP_SUBMISSION_DATE DATE, 
	PREVIOUS_PROPCODE VARCHAR2(32), 
	EU_SUPPORTED VARCHAR2(1), 
	REALSHIFTS NUMBER, 
	DESCRIPTION CLOB, 
	CONTACT_NAME VARCHAR2(90), 
	EARTH_SCIENCES VARCHAR2(1), 
	MATERIALS_SCIENCE VARCHAR2(1), 
	PHYSICAL_CHEM VARCHAR2(1), 
	INDUSTRY_COLLABORATION VARCHAR2(1), 
	INS_ID NUMBER, 
	CMT_ID VARCHAR2(30), 
	RESEARCH_AREA VARCHAR2(3), 
	ICTP_SUPPORT VARCHAR2(1), 
	USR_LASTNAME VARCHAR2(40), 
	REQUIRED_BML_NAME VARCHAR2(25), 
	FEASIBILITY VARCHAR2(1), 
	REQ_ALT_BML_NAME VARCHAR2(25), 
	BML_LOGICAL_OPERATOR VARCHAR2(3), 
	REQ_ELECTRON_BEAM VARCHAR2(1), 
	REQ_APPLICATION_CATEGORY VARCHAR2(1), 
	ALLOCATION_MAIL VARCHAR2(1), 
	DISCIPLINE VARCHAR2(2), 
	SUB_DISCIPLINE VARCHAR2(8), 
	ACHIEVEMENTS CLOB, 
	SEMESTER NUMBER, 
	EU_SUPPORT_CRUCIAL VARCHAR2(1), 
	AUTOSCHEDULING VARCHAR2(1), 
	AUTOSCHEDULE_COUNTER NUMBER, 
	LONGTERM_COMMENTS VARCHAR2(220), 
	EMAIL_ACHIEV_EXPREP DATE, 
	EU_REFUNDABLE_DAYS NUMBER, 
	MONTHLY VARCHAR2(1), 
	ICTP_SUPPORTED NUMBER, 
	FACILITY VARCHAR2(1), 
	POLARIZATION VARCHAR2(4), 
	TUNABILITY NUMBER, 
	SAMPLE_TEMPERATURE NUMBER, 
	LAST_MINUTE VARCHAR2(1), 
	BIOSTRUCTX_CODE VARCHAR2(10), 
	IAEA VARCHAR2(1), 
	WAYFORLIGHTS VARCHAR2(1), 
	FERMI_MODE NUMBER, 
	ASSIGNMENT_MAIL VARCHAR2(1), 
	LASERLAB_FUNDED VARCHAR2(1), 
	LASERLAB_REQUEST VARCHAR2(20), 
	CULTURAL_HERITAGE VARCHAR2(1), 
	LAST_CHANGE DATE, 
	FUND_SOURCE NUMBER(4,0), 
	NOTES CLOB
);
--------------------------------------------------------

CREATE TABLE PROPOSALS_BCK_JULY_4_22 --Back-up for proposals
   (	ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(255) NOT NULL ENABLE, 
	USER_CATEGORY VARCHAR2(1) NOT NULL ENABLE, 
	RESEARCH_CATEGORY VARCHAR2(1), 
	EU_SUPPORT VARCHAR2(1) NOT NULL ENABLE, 
	PHYSICS VARCHAR2(1) NOT NULL ENABLE, 
	CHEMISTRY VARCHAR2(1) NOT NULL ENABLE, 
	MEDICAL VARCHAR2(1) NOT NULL ENABLE, 
	LIFE_SCIENCES VARCHAR2(1) NOT NULL ENABLE, 
	TECH_INSTRUMENTATION VARCHAR2(1) NOT NULL ENABLE, 
	OTHER VARCHAR2(50), 
	SHIFTS NUMBER(38,0) NOT NULL ENABLE, 
	ELECTRON_BEAM VARCHAR2(1), 
	PROPOSAL_CATEGORY VARCHAR2(1) NOT NULL ENABLE, 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ENERGY VARCHAR2(255), 
	RESOLUTION VARCHAR2(80), 
	OTHER_REQUIREMENTS VARCHAR2(255), 
	SAMPLE_TREATMENT VARCHAR2(400), 
	AVAILABLE_EQUIPMENT VARCHAR2(400), 
	ADDITIONAL_EQUIPMENT VARCHAR2(255), 
	OFFLINE_FACILITIES VARCHAR2(255), 
	STATUS VARCHAR2(1) NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	LOCAL_CONTACT_ID NUMBER, 
	SUBMISSION_DATE DATE, 
	BML_NAME VARCHAR2(25), 
	PROP_SUBMISSION_DATE DATE, 
	PREVIOUS_PROPCODE VARCHAR2(32), 
	EU_SUPPORTED VARCHAR2(1), 
	REALSHIFTS NUMBER, 
	DESCRIPTION CLOB, 
	CONTACT_NAME VARCHAR2(90), 
	EARTH_SCIENCES VARCHAR2(1), 
	MATERIALS_SCIENCE VARCHAR2(1), 
	PHYSICAL_CHEM VARCHAR2(1), 
	INDUSTRY_COLLABORATION VARCHAR2(1), 
	INS_ID NUMBER, 
	CMT_ID VARCHAR2(30), 
	RESEARCH_AREA VARCHAR2(3), 
	ICTP_SUPPORT VARCHAR2(1), 
	USR_LASTNAME VARCHAR2(40), 
	REQUIRED_BML_NAME VARCHAR2(25), 
	FEASIBILITY VARCHAR2(1), 
	REQ_ALT_BML_NAME VARCHAR2(25), 
	BML_LOGICAL_OPERATOR VARCHAR2(3), 
	REQ_ELECTRON_BEAM VARCHAR2(1), 
	REQ_APPLICATION_CATEGORY VARCHAR2(1), 
	ALLOCATION_MAIL VARCHAR2(1), 
	DISCIPLINE VARCHAR2(2), 
	SUB_DISCIPLINE VARCHAR2(8), 
	ACHIEVEMENTS CLOB, 
	SEMESTER NUMBER, 
	EU_SUPPORT_CRUCIAL VARCHAR2(1), 
	AUTOSCHEDULING VARCHAR2(1), 
	AUTOSCHEDULE_COUNTER NUMBER, 
	LONGTERM_COMMENTS VARCHAR2(220), 
	EMAIL_ACHIEV_EXPREP DATE, 
	EU_REFUNDABLE_DAYS NUMBER, 
	MONTHLY VARCHAR2(1), 
	ICTP_SUPPORTED NUMBER, 
	FACILITY VARCHAR2(1), 
	POLARIZATION VARCHAR2(4), 
	TUNABILITY NUMBER, 
	SAMPLE_TEMPERATURE NUMBER, 
	LAST_MINUTE VARCHAR2(1), 
	BIOSTRUCTX_CODE VARCHAR2(10), 
	IAEA VARCHAR2(1), 
	WAYFORLIGHTS VARCHAR2(1), 
	FERMI_MODE NUMBER, 
	ASSIGNMENT_MAIL VARCHAR2(1), 
	LASERLAB_FUNDED VARCHAR2(1), 
	LASERLAB_REQUEST VARCHAR2(20), 
	CULTURAL_HERITAGE VARCHAR2(1), 
	LAST_CHANGE DATE, 
	FUND_SOURCE NUMBER(4,0), 
	NOTES CLOB
);
--------------------------------------------------------

CREATE TABLE PROPOSALS_BCK_MZ --Back-up for proposals
   (	ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(255) NOT NULL ENABLE, 
	USER_CATEGORY VARCHAR2(1) NOT NULL ENABLE, 
	RESEARCH_CATEGORY VARCHAR2(1), 
	EU_SUPPORT VARCHAR2(1) NOT NULL ENABLE, 
	PHYSICS VARCHAR2(1) NOT NULL ENABLE, 
	CHEMISTRY VARCHAR2(1) NOT NULL ENABLE, 
	MEDICAL VARCHAR2(1) NOT NULL ENABLE, 
	LIFE_SCIENCES VARCHAR2(1) NOT NULL ENABLE, 
	TECH_INSTRUMENTATION VARCHAR2(1) NOT NULL ENABLE, 
	OTHER VARCHAR2(50), 
	SHIFTS NUMBER(38,0) NOT NULL ENABLE, 
	ELECTRON_BEAM VARCHAR2(1), 
	PROPOSAL_CATEGORY VARCHAR2(1) NOT NULL ENABLE, 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ENERGY VARCHAR2(255), 
	RESOLUTION VARCHAR2(80), 
	OTHER_REQUIREMENTS VARCHAR2(255), 
	SAMPLE_TREATMENT VARCHAR2(400), 
	AVAILABLE_EQUIPMENT VARCHAR2(400), 
	ADDITIONAL_EQUIPMENT VARCHAR2(255), 
	OFFLINE_FACILITIES VARCHAR2(255), 
	STATUS VARCHAR2(1) NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	LOCAL_CONTACT_ID NUMBER, 
	SUBMISSION_DATE DATE, 
	BML_NAME VARCHAR2(25), 
	PROP_SUBMISSION_DATE DATE, 
	PREVIOUS_PROPCODE VARCHAR2(32), 
	EU_SUPPORTED VARCHAR2(1), 
	REALSHIFTS NUMBER, 
	DESCRIPTION CLOB, 
	CONTACT_NAME VARCHAR2(90), 
	EARTH_SCIENCES VARCHAR2(1), 
	MATERIALS_SCIENCE VARCHAR2(1), 
	PHYSICAL_CHEM VARCHAR2(1), 
	INDUSTRY_COLLABORATION VARCHAR2(1), 
	INS_ID NUMBER, 
	CMT_ID VARCHAR2(30), 
	RESEARCH_AREA VARCHAR2(3), 
	ICTP_SUPPORT VARCHAR2(1), 
	USR_LASTNAME VARCHAR2(40), 
	REQUIRED_BML_NAME VARCHAR2(25), 
	FEASIBILITY VARCHAR2(1), 
	REQ_ALT_BML_NAME VARCHAR2(25), 
	BML_LOGICAL_OPERATOR VARCHAR2(3), 
	REQ_ELECTRON_BEAM VARCHAR2(1), 
	REQ_APPLICATION_CATEGORY VARCHAR2(1), 
	ALLOCATION_MAIL VARCHAR2(1), 
	DISCIPLINE VARCHAR2(2), 
	SUB_DISCIPLINE VARCHAR2(8), 
	ACHIEVEMENTS CLOB, 
	SEMESTER NUMBER, 
	EU_SUPPORT_CRUCIAL VARCHAR2(1), 
	AUTOSCHEDULING VARCHAR2(1), 
	AUTOSCHEDULE_COUNTER NUMBER, 
	LONGTERM_COMMENTS VARCHAR2(220), 
	EMAIL_ACHIEV_EXPREP DATE, 
	EU_REFUNDABLE_DAYS NUMBER, 
	MONTHLY VARCHAR2(1), 
	ICTP_SUPPORTED NUMBER, 
	FACILITY VARCHAR2(1), 
	POLARIZATION VARCHAR2(4), 
	TUNABILITY NUMBER, 
	SAMPLE_TEMPERATURE NUMBER, 
	LAST_MINUTE VARCHAR2(1), 
	BIOSTRUCTX_CODE VARCHAR2(10), 
	IAEA VARCHAR2(1), 
	WAYFORLIGHTS VARCHAR2(1), 
	FERMI_MODE NUMBER, 
	ASSIGNMENT_MAIL VARCHAR2(1), 
	LASERLAB_FUNDED VARCHAR2(1), 
	LASERLAB_REQUEST VARCHAR2(20), 
	CULTURAL_HERITAGE VARCHAR2(1), 
	LAST_CHANGE DATE, 
	FUND_SOURCE NUMBER(4,0)
);
--------------------------------------------------------

CREATE TABLE PROPOSALS_OCT_2018 -- Description: Backup
   (	ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(255) NOT NULL ENABLE, 
	USER_CATEGORY VARCHAR2(1) NOT NULL ENABLE, 
	RESEARCH_CATEGORY VARCHAR2(1), 
	EU_SUPPORT VARCHAR2(1) NOT NULL ENABLE, 
	PHYSICS VARCHAR2(1) NOT NULL ENABLE, 
	CHEMISTRY VARCHAR2(1) NOT NULL ENABLE, 
	MEDICAL VARCHAR2(1) NOT NULL ENABLE, 
	LIFE_SCIENCES VARCHAR2(1) NOT NULL ENABLE, 
	TECH_INSTRUMENTATION VARCHAR2(1) NOT NULL ENABLE, 
	OTHER VARCHAR2(50), 
	SHIFTS NUMBER(38,0) NOT NULL ENABLE, 
	ELECTRON_BEAM VARCHAR2(1), 
	PROPOSAL_CATEGORY VARCHAR2(1) NOT NULL ENABLE, 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ENERGY VARCHAR2(255), 
	RESOLUTION VARCHAR2(80), 
	OTHER_REQUIREMENTS VARCHAR2(255), 
	SAMPLE_TREATMENT VARCHAR2(400), 
	AVAILABLE_EQUIPMENT VARCHAR2(400), 
	ADDITIONAL_EQUIPMENT VARCHAR2(255), 
	OFFLINE_FACILITIES VARCHAR2(255), 
	STATUS VARCHAR2(1) NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	LOCAL_CONTACT_ID NUMBER, 
	SUBMISSION_DATE DATE, 
	BML_NAME VARCHAR2(25), 
	PROP_SUBMISSION_DATE DATE, 
	PREVIOUS_PROPCODE VARCHAR2(32), 
	EU_SUPPORTED VARCHAR2(1), 
	REALSHIFTS NUMBER, 
	DESCRIPTION CLOB, 
	CONTACT_NAME VARCHAR2(90), 
	EARTH_SCIENCES VARCHAR2(1), 
	MATERIALS_SCIENCE VARCHAR2(1), 
	PHYSICAL_CHEM VARCHAR2(1), 
	INDUSTRY_COLLABORATION VARCHAR2(1), 
	INS_ID NUMBER, 
	CMT_ID VARCHAR2(30), 
	RESEARCH_AREA VARCHAR2(3), 
	ICTP_SUPPORT VARCHAR2(1), 
	USR_LASTNAME VARCHAR2(40), 
	REQUIRED_BML_NAME VARCHAR2(25), 
	FEASIBILITY VARCHAR2(1), 
	REQ_ALT_BML_NAME VARCHAR2(25), 
	BML_LOGICAL_OPERATOR VARCHAR2(3), 
	REQ_ELECTRON_BEAM VARCHAR2(1), 
	REQ_APPLICATION_CATEGORY VARCHAR2(1), 
	ALLOCATION_MAIL VARCHAR2(1), 
	DISCIPLINE VARCHAR2(2), 
	SUB_DISCIPLINE VARCHAR2(8), 
	ACHIEVEMENTS CLOB, 
	SEMESTER NUMBER, 
	EU_SUPPORT_CRUCIAL VARCHAR2(1), 
	AUTOSCHEDULING VARCHAR2(1), 
	AUTOSCHEDULE_COUNTER NUMBER, 
	LONGTERM_COMMENTS VARCHAR2(220), 
	EMAIL_ACHIEV_EXPREP DATE, 
	EU_REFUNDABLE_DAYS NUMBER, 
	MONTHLY VARCHAR2(1), 
	ICTP_SUPPORTED NUMBER, 
	FACILITY VARCHAR2(1), 
	POLARIZATION VARCHAR2(4), 
	TUNABILITY NUMBER, 
	SAMPLE_TEMPERATURE NUMBER, 
	LAST_MINUTE VARCHAR2(1), 
	BIOSTRUCTX_CODE VARCHAR2(10), 
	IAEA VARCHAR2(1), 
	WAYFORLIGHTS VARCHAR2(1), 
	FERMI_MODE NUMBER, 
	ASSIGNMENT_MAIL VARCHAR2(1), 
	LASERLAB_FUNDED VARCHAR2(1), 
	LASERLAB_REQUEST VARCHAR2(20), 
	CULTURAL_HERITAGE VARCHAR2(1), 
	LAST_CHANGE DATE, 
	FUND_SOURCE NUMBER(4,0), 
	NOTES CLOB
);
--------------------------------------------------------

CREATE TABLE PROPOSALS_OCT_3_2023 -- Description: Backup
   (	ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(255) NOT NULL ENABLE, 
	USER_CATEGORY VARCHAR2(1) NOT NULL ENABLE, 
	RESEARCH_CATEGORY VARCHAR2(1), 
	EU_SUPPORT VARCHAR2(1) NOT NULL ENABLE, 
	PHYSICS VARCHAR2(1) NOT NULL ENABLE, 
	CHEMISTRY VARCHAR2(1) NOT NULL ENABLE, 
	MEDICAL VARCHAR2(1) NOT NULL ENABLE, 
	LIFE_SCIENCES VARCHAR2(1) NOT NULL ENABLE, 
	TECH_INSTRUMENTATION VARCHAR2(1) NOT NULL ENABLE, 
	OTHER VARCHAR2(50), 
	SHIFTS NUMBER(38,0) NOT NULL ENABLE, 
	ELECTRON_BEAM VARCHAR2(1), 
	PROPOSAL_CATEGORY VARCHAR2(1) NOT NULL ENABLE, 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ENERGY VARCHAR2(255), 
	RESOLUTION VARCHAR2(80), 
	OTHER_REQUIREMENTS VARCHAR2(255), 
	SAMPLE_TREATMENT VARCHAR2(400), 
	AVAILABLE_EQUIPMENT VARCHAR2(400), 
	ADDITIONAL_EQUIPMENT VARCHAR2(255), 
	OFFLINE_FACILITIES VARCHAR2(255), 
	STATUS VARCHAR2(1) NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	LOCAL_CONTACT_ID NUMBER, 
	SUBMISSION_DATE DATE, 
	BML_NAME VARCHAR2(25), 
	PROP_SUBMISSION_DATE DATE, 
	PREVIOUS_PROPCODE VARCHAR2(32), 
	EU_SUPPORTED VARCHAR2(1), 
	REALSHIFTS NUMBER, 
	DESCRIPTION CLOB, 
	CONTACT_NAME VARCHAR2(90), 
	EARTH_SCIENCES VARCHAR2(1), 
	MATERIALS_SCIENCE VARCHAR2(1), 
	PHYSICAL_CHEM VARCHAR2(1), 
	INDUSTRY_COLLABORATION VARCHAR2(1), 
	INS_ID NUMBER, 
	CMT_ID VARCHAR2(30), 
	RESEARCH_AREA VARCHAR2(3), 
	ICTP_SUPPORT VARCHAR2(1), 
	USR_LASTNAME VARCHAR2(40), 
	REQUIRED_BML_NAME VARCHAR2(25), 
	FEASIBILITY VARCHAR2(1), 
	REQ_ALT_BML_NAME VARCHAR2(25), 
	BML_LOGICAL_OPERATOR VARCHAR2(3), 
	REQ_ELECTRON_BEAM VARCHAR2(1), 
	REQ_APPLICATION_CATEGORY VARCHAR2(1), 
	ALLOCATION_MAIL VARCHAR2(1), 
	DISCIPLINE VARCHAR2(2), 
	SUB_DISCIPLINE VARCHAR2(8), 
	ACHIEVEMENTS CLOB, 
	SEMESTER NUMBER, 
	EU_SUPPORT_CRUCIAL VARCHAR2(1), 
	AUTOSCHEDULING VARCHAR2(1), 
	AUTOSCHEDULE_COUNTER NUMBER, 
	LONGTERM_COMMENTS VARCHAR2(220), 
	EMAIL_ACHIEV_EXPREP DATE, 
	EU_REFUNDABLE_DAYS NUMBER, 
	MONTHLY VARCHAR2(1), 
	ICTP_SUPPORTED NUMBER, 
	FACILITY VARCHAR2(1), 
	POLARIZATION VARCHAR2(4), 
	TUNABILITY NUMBER, 
	SAMPLE_TEMPERATURE NUMBER, 
	LAST_MINUTE VARCHAR2(1), 
	BIOSTRUCTX_CODE VARCHAR2(10), 
	IAEA VARCHAR2(1), 
	WAYFORLIGHTS VARCHAR2(1), 
	FERMI_MODE NUMBER, 
	ASSIGNMENT_MAIL VARCHAR2(1), 
	LASERLAB_FUNDED VARCHAR2(1), 
	LASERLAB_REQUEST VARCHAR2(20), 
	CULTURAL_HERITAGE VARCHAR2(1), 
	LAST_CHANGE DATE, 
	FUND_SOURCE NUMBER(4,0), 
	NOTES CLOB
);
--------------------------------------------------------

CREATE TABLE PROPOSALS_STATUS 
   (	CODE VARCHAR2(1), 
	NAME VARCHAR2(50)
);
--------------------------------------------------------

CREATE TABLE PROPOSALS_THRESHOLD 
   (	SEM NUMBER(3,0) NOT NULL ENABLE, 
	THRESHOLD FLOAT(126) NOT NULL ENABLE, 
	ADDED_EDITED VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT PROPOSALS_THRESHOLD_PK PRIMARY KEY (SEM)
);
--------------------------------------------------------

CREATE TABLE PROP_ETHICAL_INFOS 
   (	CHILDREN VARCHAR2(1), 
	NOT_ABLE VARCHAR2(1), 
	VOLUNTEERS VARCHAR2(1), 
	GENETIC VARCHAR2(1), 
	BIOLOGICAL VARCHAR2(1), 
	DATA_COLLECTION VARCHAR2(1), 
	EMBRYOS VARCHAR2(1), 
	FOETAL VARCHAR2(1), 
	EMBRYONIC_STEM VARCHAR2(1), 
	INFORMATION VARCHAR2(1), 
	TRACKING VARCHAR2(1), 
	ANIMALS VARCHAR2(1), 
	TRANSGENIC_LAB VARCHAR2(1), 
	TRANSGENIC_FARM VARCHAR2(1), 
	CLONED_FARM VARCHAR2(1), 
	NON_HUMAN_PRIMATES VARCHAR2(1), 
	LOCAL_RESOURCES VARCHAR2(1), 
	LOCAL_COMMUNITY VARCHAR2(1), 
	MILITARY VARCHAR2(1), 
	TERRORIST VARCHAR2(1), 
	PROP_ID NUMBER, 
	USR_ID NUMBER, 
	SUBMISSION_DATE DATE, 
	 CONSTRAINT FK_ETHICAL_PROP_ID FOREIGN KEY (PROP_ID)
	  REFERENCES PROPOSALS (ID) ENABLE, 
	 CONSTRAINT FK_PROP_ETHICAL_INFOS_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE PROTEIN_CRYSTALLOGRAPHY_USERS 
   (	EMAIL VARCHAR2(300), 
	LANGUAGE VARCHAR2(2)
);
--------------------------------------------------------

CREATE TABLE PROVINCE_ITALIANE 
   (	COD_PROVINCIA VARCHAR2(3) NOT NULL ENABLE, 
	NOME VARCHAR2(40), 
	SIGLA VARCHAR2(2), 
	COD_REGIONE VARCHAR2(2), 
	REGIONE VARCHAR2(40), 
	RIPARTIZIONE_GEOGRAFICA VARCHAR2(30), 
	 CONSTRAINT PROVINCE_ITALIANE_UK1 UNIQUE (SIGLA)
    
	 CONSTRAINT PROVINCE_ITALIANE_PK PRIMARY KEY (COD_PROVINCIA)
);
--------------------------------------------------------

CREATE TABLE PUBLI --Description = Publication details 
   (	PBL_ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(1024), 
	CATEGORY VARCHAR2(64) NOT NULL ENABLE, 
	WORK_DONE_ELE CHAR(1) DEFAULT 'N' NOT NULL ENABLE, -- work_done_ele: Y= Yes, P = 'Yes, only in part', N = No
	ELE_AUTHOR CHAR(1) DEFAULT 'N' NOT NULL ENABLE, -- ele_author: Y = Yes, N = No
	JOURNAL_NAME VARCHAR2(128), 
	VOLUME VARCHAR2(128), 
	ISSUE VARCHAR2(32), 
	QTR VARCHAR2(20), 
	YEAR NUMBER, 
	BEAM_1 VARCHAR2(30), 
	BEAM_2 VARCHAR2(30), 
	BEAM_3 VARCHAR2(30), 
	BEAM_4 VARCHAR2(30), 
	PROP_1 NUMBER, 
	PROP_2 NUMBER, 
	PROP_3 NUMBER, 
	PROP_4 NUMBER, 
	COMMENTS VARCHAR2(1024), 
	EMAIL VARCHAR2(255), 
	PHONE VARCHAR2(50), 
	ELE_NUM VARCHAR2(20), 
	THES_TYPE VARCHAR2(30), 
	INSTITUTION VARCHAR2(50), 
	CITY_PUB VARCHAR2(30), 
	COUNTRY_PUB VARCHAR2(30), 
	PATENT_NUMB VARCHAR2(30), 
	REVIEW VARCHAR2(50), 
	PUB_TYPE VARCHAR2(50), 
	REVISION VARCHAR2(30), 
	BOOK_TITLE VARCHAR2(255), 
	PUBLISHER VARCHAR2(100), 
	EDITION VARCHAR2(50), 
	CONFERENCE VARCHAR2(128), 
	PBL_TYPE CHAR(1) NOT NULL ENABLE, -- pbl_type: B=Book or Book Chapter, C=Conference Presentations, G=SESAME Highlights, I=Internal SESAME Staff Reports, J=Journal Article, P=Patent, R=Contributed News Articles, Book Reviews, T=Thesis
	STATUS CHAR(1) DEFAULT 'N' NOT NULL ENABLE, -- status: Y =  Validated, N = Submitted 
	EDITOR VARCHAR2(50), 
	ADVISOR VARCHAR2(50), 
	DAY NUMBER, 
	PRES_TYPE VARCHAR2(10), 
	FPAGE VARCHAR2(10), 
	UE_SUPPORT CHAR(1), 
	ICTP_SUPPORT CHAR(1), 
	OTHER VARCHAR2(256), 
	SUBMISSION_DATE DATE, 
	USR_ID NUMBER, 
	OTHER_BEAM VARCHAR2(30), 
	OTHER_LAB VARCHAR2(50), 
	OTHER_PUBLI_NAME VARCHAR2(128), 
	CONF_CITY VARCHAR2(50), 
	CONF_COUNTRY VARCHAR2(40), 
	CONF_DATE DATE, 
	URL VARCHAR2(2000), 
	DOI VARCHAR2(4000), 
	REVIEW_PANEL VARCHAR2(20), 
	IN_HOUSE VARCHAR2(20), 
	COLLABORATION VARCHAR2(20), 
	ILO VARCHAR2(20), 
	REVIEW_WORK VARCHAR2(20), 
	LABORATORY VARCHAR2(40), 
	SERIAL_NUMBER VARCHAR2(200), 
	FROM_PAGE VARCHAR2(20), 
	TO_PAGE VARCHAR2(20), 
	LABORATORY_2 VARCHAR2(40), 
	LABORATORY_3 VARCHAR2(40), 
	WORK_DONE_CERIC CHAR(1), 
	CERIC_SUPPORT CHAR(1), 
	 CONSTRAINT PUBLI_PK PRIMARY KEY (PBL_ID)
    
	 CONSTRAINT FK_PUBLI_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);

COMMENT ON COLUMN PUBLI.WORK_DONE_ELE IS 'List = select code, description from list_of_values where list=''PubliWorkDoneEle'''
COMMENT ON COLUMN PUBLI.CONF_COUNTRY IS 'List = select code, name from countries'
COMMENT ON COLUMN PUBLI.COUNTRY_PUB IS 'List = select code, name from countries'
--------------------------------------------------------

CREATE TABLE PUBLIJRC 
   (	TITLE VARCHAR2(128) NOT NULL ENABLE, 
	IMPACT NUMBER, 
	IMMEDIACY NUMBER, 
	TYPE CHAR(1), 
	ISSN VARCHAR2(20), 
	 CONSTRAINT SYS_C0048515 UNIQUE (TITLE)
);
--------------------------------------------------------

CREATE TABLE PUBLI_AUT --Deascription: Publication author(s) 
   (	ID NUMBER NOT NULL ENABLE, 
	PBL_ID NUMBER NOT NULL ENABLE, 
	AUT_NAME VARCHAR2(128), 
	AUT_IN VARCHAR2(10), 
	AUT_COUNTRY VARCHAR2(40), 
	AUT_ID NUMBER, 
	USR_ID NUMBER, 
	 CONSTRAINT PUBLI_AUT_PK PRIMARY KEY (ID)
    
	 CONSTRAINT PUBLI_AUT_FK1 FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE, 
	 CONSTRAINT PUBLI_AUT_PUBLI_FK1 FOREIGN KEY (PBL_ID)
	  REFERENCES PUBLI (PBL_ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE PUBLI_ITEMS
   (	PBL_ID NUMBER NOT NULL ENABLE, 
	CODE VARCHAR2(30) NOT NULL ENABLE, -- code: LAB = Lab, USG = Beamline, PRP = Proposal
	ITEM_TYPE VARCHAR2(3) NOT NULL ENABLE, 
	ITEM_ORD NUMBER(38,0), 
	 CONSTRAINT PUBLI_ITEMS_PK PRIMARY KEY (PBL_ID, CODE)
    
	 CONSTRAINT FK_PUBLI_ITEMS_PUBLI_PBL_ID FOREIGN KEY (PBL_ID)
	  REFERENCES PUBLI (PBL_ID) ON DELETE CASCADE ENABLE
);
--------------------------------------------------------

CREATE TABLE PUBLI_SJR 
   (	YEAR NUMBER NOT NULL ENABLE, 
	RNK NUMBER NOT NULL ENABLE, 
	JOURNAL VARCHAR2(500), 
	ISSN VARCHAR2(10), 
	SJR NUMBER, 
	HIDX NUMBER, 
	TDOCS NUMBER, 
	TDOCS3Y NUMBER, 
	TREFS NUMBER, 
	TREFS3Y NUMBER, 
	CDOCS3Y NUMBER, 
	CDOCS2Y NUMBER, 
	REFDOCRATIO NUMBER, 
	COUNTRY VARCHAR2(25), 
	JOURNAL_TYPE VARCHAR2(1), 
	 CONSTRAINT PUBLI_SJR_PK PRIMARY KEY (YEAR, RNK)
);
--------------------------------------------------------

CREATE TABLE PUBLI_SJR_TABLES 
   (	YEAR NUMBER, 
	SJR CLOB
);
--------------------------------------------------------

CREATE TABLE QUARTERS 
   (	NAME VARCHAR2(20) NOT NULL ENABLE, 
	 UNIQUE (NAME)
);
--------------------------------------------------------

CREATE TABLE REGISTRATIONS 
   (	USR_ID NUMBER, 
	CODE VARCHAR2(30), 
	REGISTRATION_DATE DATE
);
   COMMENT ON COLUMN REGISTRATIONS.CODE IS 'Label=Validation code'
--------------------------------------------------------

CREATE TABLE RENTAL_CAR 
   (	ACCESS_ID NUMBER(22,0) NOT NULL ENABLE, 
	FLIGHT_CODE VARCHAR2(10), 
	OTHER_PICK_UP_LOC VARCHAR2(30), 
	OTHER_RETURN_LOC VARCHAR2(30), 
	PICK_UP_LOC VARCHAR2(10), 
	PICK_UP_TIME DATE, 
	RETURN_LOC VARCHAR2(10), 
	RETURN_TIME DATE
);
--------------------------------------------------------

CREATE TABLE RESOURCES 
   (	BUILDING VARCHAR2(10) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(100) NOT NULL ENABLE, 
	FLOOR VARCHAR2(20) NOT NULL ENABLE, 
	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(60) NOT NULL ENABLE, 
	RESOURCE_GROUP_ID NUMBER NOT NULL ENABLE, 
	ROOM VARCHAR2(10) NOT NULL ENABLE, 
	NEED_APPROVE VARCHAR2(1), 
	PRIO NUMBER, 
	RES_TYPE VARCHAR2(1), 
	PHONE VARCHAR2(4), 
	ROUND_ROW VARCHAR2(1), 
	 CONSTRAINT PK_RESOURCES_ID PRIMARY KEY (ID)
    
	 CONSTRAINT RESOURCES_RES_GRP_ID_FK FOREIGN KEY (RESOURCE_GROUP_ID)
	  REFERENCES RESOURCE_GROUPS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE RESOURCE_EVENTS 
   (	DATE_END DATE NOT NULL ENABLE, 
	DATE_END_SCHEDULING DATE, 
	DATE_START DATE NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(200), 
	GENERATOR_ID NUMBER, 
	ID NUMBER NOT NULL ENABLE, 
	LAYOUT VARCHAR2(1), 
	NOTES VARCHAR2(2000), 
	OVERHEAD_PROJECTOR VARCHAR2(1), 
	PEOPLE_NUMBER NUMBER NOT NULL ENABLE, 
	PERIODICITY VARCHAR2(2) NOT NULL ENABLE, 
	RESOURCE_ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(50) NOT NULL ENABLE, 
	TYPE VARCHAR2(1) NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	UTILIZER_ID NUMBER NOT NULL ENABLE, 
	VIDEO_PROJECTOR VARCHAR2(1), 
	STATUS VARCHAR2(1), 
	URL VARCHAR2(1000), 
	REMIND_MINUTES NUMBER, 
	UV_APPROVE VARCHAR2(1), 
	UV_WHEN DATE, 
	UV_MESSAGE VARCHAR2(500), 
	UV_USR_ID NUMBER, 
	 CONSTRAINT RESOURCE_EVENTS_PK PRIMARY KEY (ID)
    
	 CONSTRAINT FK_RESOURCE_EVENTS_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE, 
	 CONSTRAINT RESOURCE_EVENTS_GENERATOR_FK FOREIGN KEY (GENERATOR_ID)
	  REFERENCES RESOURCE_EVENTS (ID) ENABLE, 
	 CONSTRAINT RESOURCE_EVENTS_RES_ID_FK FOREIGN KEY (RESOURCE_ID)
	  REFERENCES RESOURCES (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE RESOURCE_GRANTS 
   (	ID NUMBER NOT NULL ENABLE, 
	RESOURCE_GROUP_ID NUMBER NOT NULL ENABLE, 
	ROLE_ID NUMBER NOT NULL ENABLE, 
	 CONSTRAINT RESOURCE_GRANTS_PK PRIMARY KEY (ID)
    
	 CONSTRAINT RESOURCE_GRANTS_UK1 UNIQUE (RESOURCE_GROUP_ID, ROLE_ID)
    
	 CONSTRAINT RESOURCE_GRANTS_GROUP_ID_FK FOREIGN KEY (RESOURCE_GROUP_ID)
	  REFERENCES RESOURCE_GROUPS (ID) ENABLE, 
	 CONSTRAINT RESOURCE_GRANTS_ROLE_ID_FK FOREIGN KEY (ROLE_ID)
	  REFERENCES ROLE_TYPES (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE RESOURCE_GROUPS 
   (	DESCRIPTION VARCHAR2(100), 
	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(20) NOT NULL ENABLE, 
	PRIO NUMBER, 
	 CONSTRAINT RESOURCE_GROUPS_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE RESOURCE_MANAGERS 
   (	ID NUMBER NOT NULL ENABLE, 
	RESOURCE_GROUP_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	 CONSTRAINT RESOURCE_MANAGERS_UK1 UNIQUE (RESOURCE_GROUP_ID, USR_ID)
    
	 CONSTRAINT RESOURCE_MANAGERS_PK PRIMARY KEY (ID)
    
	 CONSTRAINT RESOURCE_MANAGERS_GROUP_ID_FK FOREIGN KEY (RESOURCE_GROUP_ID)
	  REFERENCES RESOURCE_GROUPS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE RESOURCE_PARTICIPANTS 
   (	ID NUMBER NOT NULL ENABLE, 
	RESOURCE_EVENT_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	 CONSTRAINT RESOURCE_PARTICIPANTS_UK1 UNIQUE (RESOURCE_EVENT_ID, USR_ID)
    
	 CONSTRAINT RESOURCE_PARTICIPANTS_PK PRIMARY KEY (ID)
    
	 CONSTRAINT FK_RESOURCE_PARTICIP_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE, 
	 CONSTRAINT RESOURCE_PARTICIPANTS_EVT_FK FOREIGN KEY (RESOURCE_EVENT_ID)
	  REFERENCES RESOURCE_EVENTS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE ROLES 
   (	RLT_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	ID NUMBER NOT NULL ENABLE, 
	 CONSTRAINT ROL_PK PRIMARY KEY (ID)
    
	 CONSTRAINT ROL_RLT_FK FOREIGN KEY (RLT_ID)
	  REFERENCES ROLE_TYPES (ID) ENABLE
);
   COMMENT ON COLUMN ROLES.RLT_ID IS 'Label=Role,List=SELECT TO_CHAR(ID),DESCRIPTION FROM ROLE_TYPES ORDER BY DESCRIPTION'
   COMMENT ON COLUMN ROLES.ID IS 'Sequence=SEQ_ROLES_ID,Label=ID'
--------------------------------------------------------

CREATE TABLE ROLE_TYPES 
   (	ID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(50) NOT NULL ENABLE, 
	PAR_TYPE_ID NUMBER, 
	 CONSTRAINT RLT_PK PRIMARY KEY (ID)
);
   COMMENT ON COLUMN ROLE_TYPES.ID IS 'Label=Role,List=SELECT to_char(id), description FROM role_types where id not in (0,2,5) and id in (select distinct rlt_id from roles) ORDER BY DESCRIPTION'
--------------------------------------------------------

CREATE TABLE SAFETY_INFOS 
   (	ID NUMBER NOT NULL ENABLE, 
	SUBSTANCE VARCHAR2(160) NOT NULL ENABLE, 
	FORMULA VARCHAR2(80) NOT NULL ENABLE, 
	CATEGORY VARCHAR2(1) NOT NULL ENABLE, -- category: G = Gas, L = Liquid, M = Multilayer, S = Single Crystal, O = Other, B = Biocrystallography, P = Powder, s = Solid
	OTHER_CATEGORY VARCHAR2(30), 
	SAFI_SIZE NUMBER, 
	MASS NUMBER, 
	SURFACE_AREA NUMBER, 
	SPACE_GROUP VARCHAR2(30), 
	CELL_DIMENSIONS VARCHAR2(80), 
	CONTAINER VARCHAR2(60), 
	RISK VARCHAR2(1) NOT NULL ENABLE, -- risk: Y = Yes, N = No, U = Unknown
	RADIOACTIVE VARCHAR2(1) NOT NULL ENABLE, -- radioactive: Y = Yes, N = No
	CORROSIVE VARCHAR2(1) NOT NULL ENABLE, -- corrosive: Y = Yes, N = No
	CONTAMINANT VARCHAR2(1) NOT NULL ENABLE, -- contaminant: Y = Yes, N = No
	BIO_HAZARD VARCHAR2(1) NOT NULL ENABLE, -- bio_hazard: Y = Yes, N = No
	TOXIC VARCHAR2(1) NOT NULL ENABLE, -- toxic: Y = Yes, N = No
	OXIDISING VARCHAR2(1) NOT NULL ENABLE, -- oxidising: Y = Yes, N = No
	COMBUSTIVE VARCHAR2(1) NOT NULL ENABLE, -- combustive: Y = Yes, N = No
	CARCINOGENE VARCHAR2(1) NOT NULL ENABLE, -- carcinogene: Y = Yes, N = No
	INFLAMMABLE VARCHAR2(1) NOT NULL ENABLE, -- inflammable: Y = Yes, N = No
	EXPLOSIVE VARCHAR2(1) NOT NULL ENABLE, -- explosive: Y = Yes, N = No
	EXHAUST_DISPOSAL VARCHAR2(255), 
	SAMPLE_DISPOSAL VARCHAR2(1) NOT NULL ENABLE, -- sample_disposal: R = Removed by user
	STATUS VARCHAR2(1) NOT NULL ENABLE,  -- status: A = Certified , N = Not certified
	PROP_ID NUMBER NOT NULL ENABLE, 
	SAFETY_STATUS VARCHAR2(1), -- safety_status: N = Not checked, Y = Passed without prescription, W = Warning, P = Passed with prescription
	SAFETY_COMMENT VARCHAR2(255), 
	VOLUME NUMBER, 
	PRESSURE NUMBER, 
	UNATENDED VARCHAR2(10), 
	SUPPLIER VARCHAR2(40), 
	CAS VARCHAR2(15), 
	SAFETY_RECEIVED VARCHAR2(1) DEFAULT 'N', 
	USAGE_ID NUMBER, 
	 CONSTRAINT AVCON_SAFET_TOXIC_000 CHECK (TOXIC IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_SAFET_STATU_000 CHECK (STATUS IN ('A','N')) ENABLE,
	 CONSTRAINT AVCON_SAFET_SAMPL_000 CHECK (SAMPLE_DISPOSAL IN ('R','S','D')) ENABLE, 
	 CONSTRAINT AVCON_SAFET_RISK_000 CHECK (RISK IN ('Y','N','U')) ENABLE, 
	 CONSTRAINT AVCON_SAFET_RADIO_000 CHECK (RADIOACTIVE IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT AVCON_SAFET_OXIDI_000 CHECK (OXIDISING IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_SAFET_INFLA_000 CHECK (INFLAMMABLE IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_SAFET_EXPLO_000 CHECK (EXPLOSIVE IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_SAFET_CORRO_000 CHECK (CORROSIVE IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_SAFET_CONTA_000 CHECK (CONTAMINANT='Y' OR CONTAMINANT='N') ENABLE, 
	 CONSTRAINT AVCON_SAFET_COMBU_000 CHECK (COMBUSTIVE IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_SAFET_CATEG_000 CHECK (CATEGORY IN ('G','L','M','S','O','B','P','s')) ENABLE, 
	 CONSTRAINT AVCON_SAFET_CARCI_000 CHECK (CARCINOGENE IN ('Y','N')) ENABLE, 
	 CONSTRAINT AVCON_SAFET_BIO_H_000 CHECK (BIO_HAZARD IN ('Y','N')) ENABLE, 
	 CONSTRAINT SAFI_PK PRIMARY KEY (ID)
    
	 CONSTRAINT SAFI_PROP_FK FOREIGN KEY (PROP_ID)
	  REFERENCES PROPOSALS (ID) ENABLE
);

COMMENT ON COLUMN SAFETY_INFOS.CATEGORY IS 'Label=Physical state ,DefList= Other,Powder,Liquid,Single Crystal,Multilayer,Biocrystallography,Gas,Solid ,ValList= O,P,L,S,M,B,G,s'
COMMENT ON COLUMN SAFETY_INFOS.RISK IS 'Label=Risk in sample, preparation or equipment , DefList=Yes,No,Unknown, ValList=Y,N,U'
--------------------------------------------------------

CREATE TABLE SESAME_ACCEPTED_POLICEIS 
   (	ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	POLICY_ACCESPTED NUMBER NOT NULL ENABLE, 
	WHEN DATE NOT NULL ENABLE, 
	 CONSTRAINT SESAME_ACCEPTED_POLICEIS_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE SESAME_POLICIES 
   (	ID NUMBER NOT NULL ENABLE, 
	POLICY VARCHAR2(4000) NOT NULL ENABLE, 
	STATUS VARCHAR2(1), 
	TITLE VARCHAR2(500), 
	 CONSTRAINT SESAME_POLICIES_ID PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE STARTING_FUNCTIONS 
   (	ID NUMBER NOT NULL ENABLE, 
	STF_PROCEDURE VARCHAR2(50) NOT NULL ENABLE, 
	GRIDSPHERE_CID VARCHAR2(50), 
	 CONSTRAINT STF_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE STARTUP_MESSAGE 
   (	ID NUMBER NOT NULL ENABLE, 
	MSG_TYPE VARCHAR2(10), 
	BDATE DATE, 
	EDATE DATE, 
	MESSAGE VARCHAR2(4000)
);
--------------------------------------------------------

CREATE TABLE SUB_COMPETENCE
   (	CODE VARCHAR2(8), 
	COMP_CODE VARCHAR2(4), 
	DESCRIPTION VARCHAR2(50), 
	VALID_FROM DATE, 
	VALID_TO DATE
);
--------------------------------------------------------

CREATE TABLE SUMMARIES --Description: Shifts and hours summary completed experiments/proposals
   (	ID NUMBER NOT NULL ENABLE, 
	SMR_BEGIN DATE NOT NULL ENABLE, 
	SMR_END DATE NOT NULL ENABLE, 
	ASSIGNED_SHIFTS NUMBER(38,0) NOT NULL ENABLE, -- assigned_shifts: Number of assigned shifts (conversion: 1 shift = 8 hours)
	SETUP_SHIFTS NUMBER(38,0) NOT NULL ENABLE,  -- setup_shifts: Total Setup Hours (not shifts)	(conversion: 8 hours = 1 shift)
	USABLE_SHIFTS NUMBER(38,0) NOT NULL ENABLE, -- usable_shifts: Total Usable Hours (not shifts)	(conversion: 8 hours = 1 shift)
	UNUSABLE_SHIFTS NUMBER(38,0) NOT NULL ENABLE, -- unusable_shifts: Total Unuasable Hours (not shifts) (conversion: 8 hours = 1 shift)
	PROP_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER, 
	STATUS VARCHAR2(1), 
	BML_NAME VARCHAR2(25), 
	SDATE DATE, 
	EVENT_ID NUMBER, 
	 CONSTRAINT SMR_PK PRIMARY KEY (ID)
    
	 CONSTRAINT FK_SUMMARIES_PROP_ID FOREIGN KEY (PROP_ID)
	  REFERENCES PROPOSALS (ID) ENABLE, 
	 CONSTRAINT FK_SUMMARIES_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE SUO_FUND_SOURCE 
   (	ID NUMBER NOT NULL ENABLE, 
	FUND_NAME VARCHAR2(400) NOT NULL ENABLE, 
	OPERATIVE VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT FUND_SOURCE_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE SUO_GUEST_HOUSE_DEFINITION 
   (	HOUSE_ID NUMBER(2,0) NOT NULL ENABLE, 
	HOUSE_NAME VARCHAR2(20) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(50), 
	TOTAL_ROOMS NUMBER(2,0) NOT NULL ENABLE, 
	ROOM_RATE NUMBER(3,0) NOT NULL ENABLE, 
	MANAGER_ID NUMBER NOT NULL ENABLE, 
	STATUS VARCHAR2(20) NOT NULL ENABLE, -- status: A = Available, N = Not Available
	NOTES VARCHAR2(200) NOT NULL ENABLE, 
	 CONSTRAINT HOUSE_PK PRIMARY KEY (HOUSE_ID)
    
	 CONSTRAINT SUO_HOUSE_MNGRID_USERS_ID FOREIGN KEY (MANAGER_ID)
	  REFERENCES USERS (ID) ENABLE
);
   COMMENT ON COLUMN SUO_GUEST_HOUSE_DEFINITION.HOUSE_NAME IS 'Label=Guest House Name'
--------------------------------------------------------

CREATE TABLE SUO_WIFI_REQ_DEVICE 
   (	DEVICE_ID NUMBER NOT NULL ENABLE, 
	DEVICE_TYPE VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT SUO_WIFI_REQ_DEVICE_PK PRIMARY KEY (DEVICE_ID)
);
--------------------------------------------------------

CREATE TABLE SUO_WIFI_REQ_OS_LIST 
   (	OS_ID NUMBER NOT NULL ENABLE, 
	OS_NAME VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT SUO_WIFI_REQ_OS_LIST_PK PRIMARY KEY (OS_ID)
);
--------------------------------------------------------

CREATE TABLE SUO_WIFI_REQ_T 
   (	REQ_ID NUMBER NOT NULL ENABLE, 
	USER_ID NUMBER NOT NULL ENABLE, 
	DEVICE_TYPE NUMBER NOT NULL ENABLE, 
	OS NUMBER NOT NULL ENABLE, 
	MAC_ADD VARCHAR2(17) NOT NULL ENABLE, 
	SPECIAL_REQ VARCHAR2(500), 
	 CONSTRAINT SUO_WIFI_REQ_T_PK PRIMARY KEY (REQ_ID)
    
	 CONSTRAINT FK_DEVICE_TYPE FOREIGN KEY (DEVICE_TYPE)
	  REFERENCES SUO_WIFI_REQ_DEVICE (DEVICE_ID) ENABLE, 
	 CONSTRAINT FK_OS FOREIGN KEY (OS)
	  REFERENCES SUO_WIFI_REQ_OS_LIST (OS_ID) ENABLE, 
	 CONSTRAINT FK_USERID FOREIGN KEY (USER_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE SUPPORT_LAB_REQUESTS 
   (	ID NUMBER NOT NULL ENABLE, 
	LAB_ID VARCHAR2(1) NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	UTILIZER_ID NUMBER NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(500) NOT NULL ENABLE, 
	NOTES VARCHAR2(500), 
	CONSUMABLES VARCHAR2(500), 
	CONSUM_USER_SUPPLIED VARCHAR2(1), 
	COSTS NUMBER, 
	INTERNAL_NOTES VARCHAR2(500), 
	SUBMISSION_DATE DATE, 
	DELIVERY_DATE DATE, 
	CLOSING_DATE DATE, 
	STATUS VARCHAR2(1) NOT NULL ENABLE, 
	PROP_ID NUMBER, 
	LAB_ACCESS_START DATE, 
	LAB_ACCESS_END DATE, 
	LAB_ACCESS VARCHAR2(1), 
	EQUIPMENT VARCHAR2(500), 
	EQUIP_USER_SUPPLIED VARCHAR2(1), 
	WORK_ABILITY VARCHAR2(1), 
	BEAMLINE VARCHAR2(25), 
	LABORATORY VARCHAR2(50), 
	PROJECT VARCHAR2(50), 
	BADGE_REQUEST VARCHAR2(1), 
	 CONSTRAINT SYS_C00312565 PRIMARY KEY (ID)
    
	 CONSTRAINT FK_SUPPORT_LAB_REQ_PROP_ID FOREIGN KEY (PROP_ID)
	  REFERENCES PROPOSALS (ID) ENABLE, 
	 CONSTRAINT FK_SUPPORT_LAB_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE, 
	 CONSTRAINT FK_SUPPORT_LAB_UTILIZER_ID FOREIGN KEY (UTILIZER_ID)
	  REFERENCES USERS (ID) ENABLE, 
	 CONSTRAINT SUPPORT_LAB_REQUESTS_BEAM_FK1 FOREIGN KEY (BEAMLINE)
	  REFERENCES BEAMLINES (NAME) ENABLE
);
--------------------------------------------------------

CREATE TABLE SUP_EVENTS_DEF 
   (	ID NUMBER NOT NULL ENABLE, 
	NAME VARCHAR2(600) NOT NULL ENABLE, 
	STARTS_ON DATE NOT NULL ENABLE, 
	ENDS_ON DATE NOT NULL ENABLE, 
	DEADLINE_LABEL VARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT SUP_EVENTS_TABLE_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE SUP_EVENTS_PP -- Description: Details on participation in the users' meeting
   (	ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(255), 
	USER_CATEGORY VARCHAR2(1), 
	RESEARCH_CATEGORY VARCHAR2(1), 
	EU_SUPPORT VARCHAR2(1), 
	PHYSICS VARCHAR2(1), 
	CHEMISTRY VARCHAR2(1), 
	MEDICAL VARCHAR2(1), 
	LIFE_SCIENCES VARCHAR2(1), 
	TECH_INSTRUMENTATION VARCHAR2(1), 
	OTHER VARCHAR2(50), 
	SHIFTS NUMBER(38,0), 
	ELECTRON_BEAM VARCHAR2(1), 
	PROPOSAL_CATEGORY VARCHAR2(1), 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ENERGY VARCHAR2(255), 
	RESOLUTION VARCHAR2(80), 
	OTHER_REQUIREMENTS VARCHAR2(500), 
	SAMPLE_TREATMENT VARCHAR2(4000) NOT NULL ENABLE, 
	AVAILABLE_EQUIPMENT VARCHAR2(4000), 
	ADDITIONAL_EQUIPMENT VARCHAR2(255), 
	OFFLINE_FACILITIES VARCHAR2(255), 
	STATUS VARCHAR2(1), 
	USR_ID NUMBER, 
	LOCAL_CONTACT_ID NUMBER, 
	SUBMISSION_DATE DATE, 
	BML_NAME VARCHAR2(25), 
	PROP_SUBMISSION_DATE DATE, 
	PREVIOUS_PROPCODE VARCHAR2(32), 
	EU_SUPPORTED VARCHAR2(1), 
	REALSHIFTS NUMBER, 
	DESCRIPTION CLOB, 
	CONTACT_NAME VARCHAR2(90), 
	EARTH_SCIENCES VARCHAR2(1), 
	MATERIALS_SCIENCE VARCHAR2(1), 
	PHYSICAL_CHEM VARCHAR2(1), 
	INDUSTRY_COLLABORATION VARCHAR2(1), 
	INS_ID NUMBER, 
	CMT_ID VARCHAR2(30), 
	RESEARCH_AREA VARCHAR2(3), 
	ICTP_SUPPORT VARCHAR2(1), 
	USR_LASTNAME VARCHAR2(40), 
	REQUIRED_BML_NAME VARCHAR2(25), 
	FEASIBILITY VARCHAR2(1), 
	REQ_ALT_BML_NAME VARCHAR2(25), 
	BML_LOGICAL_OPERATOR VARCHAR2(3), 
	REQ_ELECTRON_BEAM VARCHAR2(1), 
	REQ_APPLICATION_CATEGORY VARCHAR2(1), 
	ALLOCATION_MAIL VARCHAR2(1), 
	DISCIPLINE VARCHAR2(2), 
	SUB_DISCIPLINE VARCHAR2(8), 
	ACHIEVEMENTS CLOB, 
	SEMESTER NUMBER, 
	EU_SUPPORT_CRUCIAL VARCHAR2(1), 
	AUTOSCHEDULING VARCHAR2(1), 
	AUTOSCHEDULE_COUNTER NUMBER, 
	LONGTERM_COMMENTS VARCHAR2(220), 
	EMAIL_ACHIEV_EXPREP DATE, 
	EU_REFUNDABLE_DAYS NUMBER, 
	MONTHLY VARCHAR2(1), 
	ICTP_SUPPORTED NUMBER, 
	FACILITY VARCHAR2(1), 
	POLARIZATION VARCHAR2(4), 
	TUNABILITY NUMBER, 
	SAMPLE_TEMPERATURE NUMBER, 
	LAST_MINUTE VARCHAR2(1), 
	BIOSTRUCTX_CODE VARCHAR2(10), 
	IAEA VARCHAR2(1), 
	WAYFORLIGHTS VARCHAR2(1), 
	FERMI_MODE NUMBER, 
	ASSIGNMENT_MAIL VARCHAR2(1), 
	LASERLAB_FUNDED VARCHAR2(1), 
	LASERLAB_REQUEST VARCHAR2(20), 
	CULTURAL_HERITAGE VARCHAR2(1), 
	LAST_CHANGE DATE, 
	FUND_SOURCE NUMBER(4,0), 
	NOTES CLOB, 
	 CONSTRAINT SUP_EVENTS_PP_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE SUP_EVENTS_PP_15TH_UM -- Description: Details on participation in the 15th Users Meeting
   (	ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(255), 
	USER_CATEGORY VARCHAR2(1), 
	RESEARCH_CATEGORY VARCHAR2(1), 
	EU_SUPPORT VARCHAR2(1), 
	PHYSICS VARCHAR2(1), 
	CHEMISTRY VARCHAR2(1), 
	MEDICAL VARCHAR2(1), 
	LIFE_SCIENCES VARCHAR2(1), 
	TECH_INSTRUMENTATION VARCHAR2(1), 
	OTHER VARCHAR2(50), 
	SHIFTS NUMBER(38,0), 
	ELECTRON_BEAM VARCHAR2(1), 
	PROPOSAL_CATEGORY VARCHAR2(1), 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ENERGY VARCHAR2(255), 
	RESOLUTION VARCHAR2(80), 
	OTHER_REQUIREMENTS VARCHAR2(500), 
	SAMPLE_TREATMENT VARCHAR2(3990) NOT NULL ENABLE, 
	AVAILABLE_EQUIPMENT VARCHAR2(4000), 
	ADDITIONAL_EQUIPMENT VARCHAR2(255), 
	OFFLINE_FACILITIES VARCHAR2(255), 
	STATUS VARCHAR2(1), 
	USR_ID NUMBER, 
	LOCAL_CONTACT_ID NUMBER, 
	SUBMISSION_DATE DATE, 
	BML_NAME VARCHAR2(25), 
	PROP_SUBMISSION_DATE DATE, 
	PREVIOUS_PROPCODE VARCHAR2(32), 
	EU_SUPPORTED VARCHAR2(1), 
	REALSHIFTS NUMBER, 
	DESCRIPTION CLOB, 
	CONTACT_NAME VARCHAR2(90), 
	EARTH_SCIENCES VARCHAR2(1), 
	MATERIALS_SCIENCE VARCHAR2(1), 
	PHYSICAL_CHEM VARCHAR2(1), 
	INDUSTRY_COLLABORATION VARCHAR2(1), 
	INS_ID NUMBER, 
	CMT_ID VARCHAR2(30), 
	RESEARCH_AREA VARCHAR2(3), 
	ICTP_SUPPORT VARCHAR2(1), 
	USR_LASTNAME VARCHAR2(40), 
	REQUIRED_BML_NAME VARCHAR2(25), 
	FEASIBILITY VARCHAR2(1), 
	REQ_ALT_BML_NAME VARCHAR2(25), 
	BML_LOGICAL_OPERATOR VARCHAR2(3), 
	REQ_ELECTRON_BEAM VARCHAR2(1), 
	REQ_APPLICATION_CATEGORY VARCHAR2(1), 
	ALLOCATION_MAIL VARCHAR2(1), 
	DISCIPLINE VARCHAR2(2), 
	SUB_DISCIPLINE VARCHAR2(8), 
	ACHIEVEMENTS CLOB, 
	SEMESTER NUMBER, 
	EU_SUPPORT_CRUCIAL VARCHAR2(1), 
	AUTOSCHEDULING VARCHAR2(1), 
	AUTOSCHEDULE_COUNTER NUMBER, 
	LONGTERM_COMMENTS VARCHAR2(220), 
	EMAIL_ACHIEV_EXPREP DATE, 
	EU_REFUNDABLE_DAYS NUMBER, 
	MONTHLY VARCHAR2(1), 
	ICTP_SUPPORTED NUMBER, 
	FACILITY VARCHAR2(1), 
	POLARIZATION VARCHAR2(4), 
	TUNABILITY NUMBER, 
	SAMPLE_TEMPERATURE NUMBER, 
	LAST_MINUTE VARCHAR2(1), 
	BIOSTRUCTX_CODE VARCHAR2(10), 
	IAEA VARCHAR2(1), 
	WAYFORLIGHTS VARCHAR2(1), 
	FERMI_MODE NUMBER, 
	ASSIGNMENT_MAIL VARCHAR2(1), 
	LASERLAB_FUNDED VARCHAR2(1), 
	LASERLAB_REQUEST VARCHAR2(20), 
	CULTURAL_HERITAGE VARCHAR2(1), 
	LAST_CHANGE DATE, 
	FUND_SOURCE NUMBER(4,0), 
	NOTES CLOB
);
--------------------------------------------------------

CREATE TABLE SUP_EVENTS_PP_16UM -- Description: Details on participation in the 16th Users Meeting
   (	ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(255), 
	USER_CATEGORY VARCHAR2(1), 
	RESEARCH_CATEGORY VARCHAR2(1), 
	EU_SUPPORT VARCHAR2(1), 
	PHYSICS VARCHAR2(1), 
	CHEMISTRY VARCHAR2(1), 
	MEDICAL VARCHAR2(1), 
	LIFE_SCIENCES VARCHAR2(1), 
	TECH_INSTRUMENTATION VARCHAR2(1), 
	OTHER VARCHAR2(50), 
	SHIFTS NUMBER(38,0), 
	ELECTRON_BEAM VARCHAR2(1), 
	PROPOSAL_CATEGORY VARCHAR2(1), 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ENERGY VARCHAR2(255), 
	RESOLUTION VARCHAR2(80), 
	OTHER_REQUIREMENTS VARCHAR2(500), 
	SAMPLE_TREATMENT VARCHAR2(4000) NOT NULL ENABLE, 
	AVAILABLE_EQUIPMENT VARCHAR2(4000), 
	ADDITIONAL_EQUIPMENT VARCHAR2(255), 
	OFFLINE_FACILITIES VARCHAR2(255), 
	STATUS VARCHAR2(1), 
	USR_ID NUMBER, 
	LOCAL_CONTACT_ID NUMBER, 
	SUBMISSION_DATE DATE, 
	BML_NAME VARCHAR2(25), 
	PROP_SUBMISSION_DATE DATE, 
	PREVIOUS_PROPCODE VARCHAR2(32), 
	EU_SUPPORTED VARCHAR2(1), 
	REALSHIFTS NUMBER, 
	DESCRIPTION CLOB, 
	CONTACT_NAME VARCHAR2(90), 
	EARTH_SCIENCES VARCHAR2(1), 
	MATERIALS_SCIENCE VARCHAR2(1), 
	PHYSICAL_CHEM VARCHAR2(1), 
	INDUSTRY_COLLABORATION VARCHAR2(1), 
	INS_ID NUMBER, 
	CMT_ID VARCHAR2(30), 
	RESEARCH_AREA VARCHAR2(3), 
	ICTP_SUPPORT VARCHAR2(1), 
	USR_LASTNAME VARCHAR2(40), 
	REQUIRED_BML_NAME VARCHAR2(25), 
	FEASIBILITY VARCHAR2(1), 
	REQ_ALT_BML_NAME VARCHAR2(25), 
	BML_LOGICAL_OPERATOR VARCHAR2(3), 
	REQ_ELECTRON_BEAM VARCHAR2(1), 
	REQ_APPLICATION_CATEGORY VARCHAR2(1), 
	ALLOCATION_MAIL VARCHAR2(1), 
	DISCIPLINE VARCHAR2(2), 
	SUB_DISCIPLINE VARCHAR2(8), 
	ACHIEVEMENTS CLOB, 
	SEMESTER NUMBER, 
	EU_SUPPORT_CRUCIAL VARCHAR2(1), 
	AUTOSCHEDULING VARCHAR2(1), 
	AUTOSCHEDULE_COUNTER NUMBER, 
	LONGTERM_COMMENTS VARCHAR2(220), 
	EMAIL_ACHIEV_EXPREP DATE, 
	EU_REFUNDABLE_DAYS NUMBER, 
	MONTHLY VARCHAR2(1), 
	ICTP_SUPPORTED NUMBER, 
	FACILITY VARCHAR2(1), 
	POLARIZATION VARCHAR2(4), 
	TUNABILITY NUMBER, 
	SAMPLE_TEMPERATURE NUMBER, 
	LAST_MINUTE VARCHAR2(1), 
	BIOSTRUCTX_CODE VARCHAR2(10), 
	IAEA VARCHAR2(1), 
	WAYFORLIGHTS VARCHAR2(1), 
	FERMI_MODE NUMBER, 
	ASSIGNMENT_MAIL VARCHAR2(1), 
	LASERLAB_FUNDED VARCHAR2(1), 
	LASERLAB_REQUEST VARCHAR2(20), 
	CULTURAL_HERITAGE VARCHAR2(1), 
	LAST_CHANGE DATE, 
	FUND_SOURCE NUMBER(4,0), 
	NOTES CLOB
);
--------------------------------------------------------

CREATE TABLE SUP_EVENTS_PP_17TH_UM -- Description: Details on participation in the 17th Users Meeting
   (	ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(255), 
	USER_CATEGORY VARCHAR2(1), 
	RESEARCH_CATEGORY VARCHAR2(1), 
	EU_SUPPORT VARCHAR2(1), 
	PHYSICS VARCHAR2(1), 
	CHEMISTRY VARCHAR2(1), 
	MEDICAL VARCHAR2(1), 
	LIFE_SCIENCES VARCHAR2(1), 
	TECH_INSTRUMENTATION VARCHAR2(1), 
	OTHER VARCHAR2(50), 
	SHIFTS NUMBER(38,0), 
	ELECTRON_BEAM VARCHAR2(1), 
	PROPOSAL_CATEGORY VARCHAR2(1), 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ENERGY VARCHAR2(255), 
	RESOLUTION VARCHAR2(80), 
	OTHER_REQUIREMENTS VARCHAR2(500), 
	SAMPLE_TREATMENT VARCHAR2(4000) NOT NULL ENABLE, 
	AVAILABLE_EQUIPMENT VARCHAR2(4000), 
	ADDITIONAL_EQUIPMENT VARCHAR2(255), 
	OFFLINE_FACILITIES VARCHAR2(255), 
	STATUS VARCHAR2(1), 
	USR_ID NUMBER, 
	LOCAL_CONTACT_ID NUMBER, 
	SUBMISSION_DATE DATE, 
	BML_NAME VARCHAR2(25), 
	PROP_SUBMISSION_DATE DATE, 
	PREVIOUS_PROPCODE VARCHAR2(32), 
	EU_SUPPORTED VARCHAR2(1), 
	REALSHIFTS NUMBER, 
	DESCRIPTION CLOB, 
	CONTACT_NAME VARCHAR2(90), 
	EARTH_SCIENCES VARCHAR2(1), 
	MATERIALS_SCIENCE VARCHAR2(1), 
	PHYSICAL_CHEM VARCHAR2(1), 
	INDUSTRY_COLLABORATION VARCHAR2(1), 
	INS_ID NUMBER, 
	CMT_ID VARCHAR2(30), 
	RESEARCH_AREA VARCHAR2(3), 
	ICTP_SUPPORT VARCHAR2(1), 
	USR_LASTNAME VARCHAR2(40), 
	REQUIRED_BML_NAME VARCHAR2(25), 
	FEASIBILITY VARCHAR2(1), 
	REQ_ALT_BML_NAME VARCHAR2(25), 
	BML_LOGICAL_OPERATOR VARCHAR2(3), 
	REQ_ELECTRON_BEAM VARCHAR2(1), 
	REQ_APPLICATION_CATEGORY VARCHAR2(1), 
	ALLOCATION_MAIL VARCHAR2(1), 
	DISCIPLINE VARCHAR2(2), 
	SUB_DISCIPLINE VARCHAR2(8), 
	ACHIEVEMENTS CLOB, 
	SEMESTER NUMBER, 
	EU_SUPPORT_CRUCIAL VARCHAR2(1), 
	AUTOSCHEDULING VARCHAR2(1), 
	AUTOSCHEDULE_COUNTER NUMBER, 
	LONGTERM_COMMENTS VARCHAR2(220), 
	EMAIL_ACHIEV_EXPREP DATE, 
	EU_REFUNDABLE_DAYS NUMBER, 
	MONTHLY VARCHAR2(1), 
	ICTP_SUPPORTED NUMBER, 
	FACILITY VARCHAR2(1), 
	POLARIZATION VARCHAR2(4), 
	TUNABILITY NUMBER, 
	SAMPLE_TEMPERATURE NUMBER, 
	LAST_MINUTE VARCHAR2(1), 
	BIOSTRUCTX_CODE VARCHAR2(10), 
	IAEA VARCHAR2(1), 
	WAYFORLIGHTS VARCHAR2(1), 
	FERMI_MODE NUMBER, 
	ASSIGNMENT_MAIL VARCHAR2(1), 
	LASERLAB_FUNDED VARCHAR2(1), 
	LASERLAB_REQUEST VARCHAR2(20), 
	CULTURAL_HERITAGE VARCHAR2(1), 
	LAST_CHANGE DATE, 
	FUND_SOURCE NUMBER(4,0), 
	NOTES CLOB
);
--------------------------------------------------------

CREATE TABLE SUP_EVENTS_PP_18_UM -- Description: Details on participation in the 18th Users Meeting
   (	ID NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(255), 
	USER_CATEGORY VARCHAR2(1), 
	RESEARCH_CATEGORY VARCHAR2(1), 
	EU_SUPPORT VARCHAR2(1), 
	PHYSICS VARCHAR2(1), 
	CHEMISTRY VARCHAR2(1), 
	MEDICAL VARCHAR2(1), 
	LIFE_SCIENCES VARCHAR2(1), 
	TECH_INSTRUMENTATION VARCHAR2(1), 
	OTHER VARCHAR2(50), 
	SHIFTS NUMBER(38,0), 
	ELECTRON_BEAM VARCHAR2(1), 
	PROPOSAL_CATEGORY VARCHAR2(1), 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ENERGY VARCHAR2(255), 
	RESOLUTION VARCHAR2(80), 
	OTHER_REQUIREMENTS VARCHAR2(500), 
	SAMPLE_TREATMENT VARCHAR2(4000) NOT NULL ENABLE, 
	AVAILABLE_EQUIPMENT VARCHAR2(4000), 
	ADDITIONAL_EQUIPMENT VARCHAR2(255), 
	OFFLINE_FACILITIES VARCHAR2(255), 
	STATUS VARCHAR2(1), 
	USR_ID NUMBER, 
	LOCAL_CONTACT_ID NUMBER, 
	SUBMISSION_DATE DATE, 
	BML_NAME VARCHAR2(25), 
	PROP_SUBMISSION_DATE DATE, 
	PREVIOUS_PROPCODE VARCHAR2(32), 
	EU_SUPPORTED VARCHAR2(1), 
	REALSHIFTS NUMBER, 
	DESCRIPTION CLOB, 
	CONTACT_NAME VARCHAR2(90), 
	EARTH_SCIENCES VARCHAR2(1), 
	MATERIALS_SCIENCE VARCHAR2(1), 
	PHYSICAL_CHEM VARCHAR2(1), 
	INDUSTRY_COLLABORATION VARCHAR2(1), 
	INS_ID NUMBER, 
	CMT_ID VARCHAR2(30), 
	RESEARCH_AREA VARCHAR2(3), 
	ICTP_SUPPORT VARCHAR2(1), 
	USR_LASTNAME VARCHAR2(40), 
	REQUIRED_BML_NAME VARCHAR2(25), 
	FEASIBILITY VARCHAR2(1), 
	REQ_ALT_BML_NAME VARCHAR2(25), 
	BML_LOGICAL_OPERATOR VARCHAR2(3), 
	REQ_ELECTRON_BEAM VARCHAR2(1), 
	REQ_APPLICATION_CATEGORY VARCHAR2(1), 
	ALLOCATION_MAIL VARCHAR2(1), 
	DISCIPLINE VARCHAR2(2), 
	SUB_DISCIPLINE VARCHAR2(8), 
	ACHIEVEMENTS CLOB, 
	SEMESTER NUMBER, 
	EU_SUPPORT_CRUCIAL VARCHAR2(1), 
	AUTOSCHEDULING VARCHAR2(1), 
	AUTOSCHEDULE_COUNTER NUMBER, 
	LONGTERM_COMMENTS VARCHAR2(220), 
	EMAIL_ACHIEV_EXPREP DATE, 
	EU_REFUNDABLE_DAYS NUMBER, 
	MONTHLY VARCHAR2(1), 
	ICTP_SUPPORTED NUMBER, 
	FACILITY VARCHAR2(1), 
	POLARIZATION VARCHAR2(4), 
	TUNABILITY NUMBER, 
	SAMPLE_TEMPERATURE NUMBER, 
	LAST_MINUTE VARCHAR2(1), 
	BIOSTRUCTX_CODE VARCHAR2(10), 
	IAEA VARCHAR2(1), 
	WAYFORLIGHTS VARCHAR2(1), 
	FERMI_MODE NUMBER, 
	ASSIGNMENT_MAIL VARCHAR2(1), 
	LASERLAB_FUNDED VARCHAR2(1), 
	LASERLAB_REQUEST VARCHAR2(20), 
	CULTURAL_HERITAGE VARCHAR2(1), 
	LAST_CHANGE DATE, 
	FUND_SOURCE NUMBER(4,0), 
	NOTES CLOB
);
--------------------------------------------------------

CREATE TABLE SUP_EV_EVALUATION -- Description: Evaluation of applications for the Users' Meeting
   (	ID NUMBER NOT NULL ENABLE, 
	SCORE NUMBER(38,0), 
	COMMENTS CLOB, 
	PROP_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	EVLT_ID NUMBER NOT NULL ENABLE, 
	RELEVANCE NUMBER, 
	ORIGINALITY NUMBER, 
	LOWRISK NUMBER, 
	NEEDELETTRA NUMBER, 
	PREVRECORD NUMBER, 
	TECHNICAL_EVLT VARCHAR2(1), 
	BML_OR_CMT VARCHAR2(25), 
	REALSHIFTS NUMBER, 
	STATUS VARCHAR2(1), 
	FINAL_SCORE NUMBER(4,2), 
	WEIGHTEDAVERAGE NUMBER(4,2), 
	COMPETENCE NUMBER(4,0), 
	QUARTER VARCHAR2(10), 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ELECTRON_BEAM VARCHAR2(1), 
	INTERNAL_COMMENTS CLOB, 
	REEDITING VARCHAR2(1), 
	REEDIT_COMMENTS CLOB, 
	FINAL VARCHAR2(20), 
	 CONSTRAINT SUP_EV_EVALUATION_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE SUP_EV_EVALUATION_1 -- Description: Evaluation of applications for the Users' Meeting
   (	ID NUMBER NOT NULL ENABLE, 
	SCORE NUMBER(38,0), 
	COMMENTS CLOB, 
	PROP_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	EVLT_ID NUMBER NOT NULL ENABLE, 
	RELEVANCE NUMBER, 
	ORIGINALITY NUMBER, 
	LOWRISK NUMBER, 
	NEEDELETTRA NUMBER, 
	PREVRECORD NUMBER, 
	TECHNICAL_EVLT VARCHAR2(1), 
	BML_OR_CMT VARCHAR2(25), 
	REALSHIFTS NUMBER, 
	STATUS VARCHAR2(1), 
	FINAL_SCORE NUMBER(4,2), 
	WEIGHTEDAVERAGE NUMBER(4,2), 
	COMPETENCE NUMBER(4,0), 
	QUARTER VARCHAR2(10), 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ELECTRON_BEAM VARCHAR2(1), 
	INTERNAL_COMMENTS CLOB, 
	REEDITING VARCHAR2(1), 
	REEDIT_COMMENTS CLOB, 
	FINAL VARCHAR2(20)
);
--------------------------------------------------------

CREATE TABLE SUP_EV_EVALUATION_17TH_UM -- Description: Evaluation of applications for the 17th Users' Meeting
   (	ID NUMBER NOT NULL ENABLE, 
	SCORE NUMBER(38,0), 
	COMMENTS CLOB, 
	PROP_ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	EVLT_ID NUMBER NOT NULL ENABLE, 
	RELEVANCE NUMBER, 
	ORIGINALITY NUMBER, 
	LOWRISK NUMBER, 
	NEEDELETTRA NUMBER, 
	PREVRECORD NUMBER, 
	TECHNICAL_EVLT VARCHAR2(1), 
	BML_OR_CMT VARCHAR2(25), 
	REALSHIFTS NUMBER, 
	STATUS VARCHAR2(1), 
	FINAL_SCORE NUMBER(4,2), 
	WEIGHTEDAVERAGE NUMBER(4,2), 
	COMPETENCE NUMBER(4,0), 
	QUARTER VARCHAR2(10), 
	APPLICATION_CATEGORY VARCHAR2(1), 
	ELECTRON_BEAM VARCHAR2(1), 
	INTERNAL_COMMENTS CLOB, 
	REEDITING VARCHAR2(1), 
	REEDIT_COMMENTS CLOB, 
	FINAL VARCHAR2(20)
);
--------------------------------------------------------

CREATE TABLE SUP_PARALLEL_SESSIONS 
   (	ID NUMBER NOT NULL ENABLE, 
	FUND_NAME VARCHAR2(400) NOT NULL ENABLE, 
	OPERATIVE VARCHAR2(1) NOT NULL ENABLE
);
--------------------------------------------------------

CREATE TABLE SUP_PERSONAL_DATA_FORM_T -- Description: Consent/Authorize name and institution to appear in the Annual Scientific Report for Member Countries.
   (	ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER, 
	REG_DATE DATE, 
	CASE1A VARCHAR2(10) NOT NULL ENABLE, 
	CASE2A VARCHAR2(10) NOT NULL ENABLE, 
	CASE2B VARCHAR2(10) NOT NULL ENABLE, 
	CASE3A VARCHAR2(10) NOT NULL ENABLE, 
	CASE3B VARCHAR2(10) NOT NULL ENABLE, 
	CASE4A VARCHAR2(10) NOT NULL ENABLE, 
	CASE5A VARCHAR2(10) NOT NULL ENABLE, 
	CASE5B VARCHAR2(10) NOT NULL ENABLE, 
	CASE6A VARCHAR2(10) NOT NULL ENABLE, 
	CASE6B VARCHAR2(10) NOT NULL ENABLE, 
	CASE7A VARCHAR2(10) NOT NULL ENABLE, -- Case7: User never participated in experiments or beamtimes but attended at least 1 users' meeting
	CASE7B VARCHAR2(10) NOT NULL ENABLE, 
	CASE8A VARCHAR2(10) NOT NULL ENABLE, -- Case8: User never participated in experiments, beamtimes or any users' meetings
	CASE8B VARCHAR2(10) NOT NULL ENABLE, 
	AUD_CHANGER NUMBER DEFAULT -1 NOT NULL ENABLE, 
	 CONSTRAINT SUP_PERSONAL_DATA_FORM_T_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE SUP_PERSONAL_DATA_FORM_T_BCK -- Description: Backup 
   (	ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER, 
	REG_DATE DATE, 
	CASE1A VARCHAR2(10) NOT NULL ENABLE, 
	CASE2A VARCHAR2(10) NOT NULL ENABLE, 
	CASE2B VARCHAR2(10) NOT NULL ENABLE, 
	CASE3A VARCHAR2(10) NOT NULL ENABLE, 
	CASE3B VARCHAR2(10) NOT NULL ENABLE, 
	CASE4A VARCHAR2(10) NOT NULL ENABLE, 
	CASE5A VARCHAR2(10) NOT NULL ENABLE, 
	CASE5B VARCHAR2(10) NOT NULL ENABLE, 
	CASE6A VARCHAR2(10) NOT NULL ENABLE, 
	CASE6B VARCHAR2(10) NOT NULL ENABLE, 
	CASE7A VARCHAR2(10) NOT NULL ENABLE, 
	CASE7B VARCHAR2(10) NOT NULL ENABLE, 
	CASE8A VARCHAR2(10) NOT NULL ENABLE, 
	CASE8B VARCHAR2(10) NOT NULL ENABLE
);
--------------------------------------------------------

CREATE TABLE SUP_TECH_PUBLI 
   (	PBL_ID NUMBER(5,0) NOT NULL ENABLE, 
	PBL_TYPE VARCHAR2(20) DEFAULT 'J' NOT NULL ENABLE, 
	AUTHORS VARCHAR2(2048) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(2048) NOT NULL ENABLE, 
	DOI VARCHAR2(100) NOT NULL ENABLE, 
	YEAR NUMBER(4,0) NOT NULL ENABLE, 
	TEAM VARCHAR2(200) NOT NULL ENABLE, 
	 CONSTRAINT SUP_TECH_PUBLI_PK PRIMARY KEY (DOI)
);
--------------------------------------------------------

CREATE TABLE TRAVEL_REQUESTS 
   (	ID NUMBER NOT NULL ENABLE, 
	USR_ID NUMBER, 
	MATRICULA VARCHAR2(6), 
	EMPLOYEE_ID NUMBER, 
	PROTOCOLLO VARCHAR2(10), 
	CDC VARCHAR2(10), 
	VDC VARCHAR2(10), 
	CONTROPARTITA VARCHAR2(10), 
	DATA_INIZIO DATE, 
	DATA_FINE DATE, 
	NAZIONE VARCHAR2(2), 
	PROVINCIA VARCHAR2(50), 
	COMUNE VARCHAR2(50), 
	LOCALITA VARCHAR2(50), 
	PRESSO VARCHAR2(100), 
	MOTIVO VARCHAR2(100), 
	DATA_INVIO DATE, 
	CAPOGRUPPO NUMBER, 
	FIRMA_CAPOGRUPPO DATE, 
	AHE_CDC_RESP NUMBER, 
	FIRMA_RESP_CDC DATE, 
	STATUS VARCHAR2(2), 
	REF_REQUEST_ID NUMBER, 
	CDC_SPESA_MAX NUMBER, 
	CAPOGRUPPO_RESPINTA VARCHAR2(250), 
	CDC_RESPINTA VARCHAR2(250), 
	 CONSTRAINT PK_TRAVELS_ID PRIMARY KEY (ID)
    
	 CONSTRAINT FK_TRAVELS_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE USERS
   (	ID NUMBER, 
	NAME VARCHAR2(40), 
	LASTNAME VARCHAR2(40), 
	EMAIL VARCHAR2(255), 
	URL VARCHAR2(255), 
	STATUS VARCHAR2(1), 
	PASSWORD VARCHAR2(20), 
	MAILING VARCHAR2(1), -- mailing: Y = Yes, N = Not Included
	INS_ID NUMBER NOT NULL ENABLE, 
	PRIVACY VARCHAR2(1), 
	GENDER VARCHAR2(2), 
	NATIONALITY VARCHAR2(4), 
	BIRTH DATE, 
	COMP_1 VARCHAR2(2), 
	COMP_2 VARCHAR2(2), 
	RESEARCHER_TYPE VARCHAR2(4), -- researcher_type: Research Fellow = REF, Academic Staff = ACS, Post Doctoral Researcher = PDOC, Doctoral Research Student = DOCR, Master Research Student = MRS, Undergraduate Student = UND, Technician = TECH, SESAME Staff = SES
	NEW_USER VARCHAR2(2), 
	BIRTH_CITY VARCHAR2(50), 
	BIRTH_CNT_ID VARCHAR2(4), 
	HOME_ADDR VARCHAR2(50), 
	HOME_CITY VARCHAR2(50), 
	HOME_CNT_ID VARCHAR2(4), 
	HOME_ZIP VARCHAR2(10), 
	SAFETY_VIDEO DATE, 
	COD_FISCALE VARCHAR2(16), 
	BIRTH_PROVINCE VARCHAR2(2), 
	BIRTH_TOWN VARCHAR2(50), 
	HOME_PROVINCE VARCHAR2(2), 
	HOME_TOWN VARCHAR2(50), 
	IDSUBJECT VARCHAR2(16), 
	CREATION_DATE DATE, 
	LAST_ACCESS DATE, 
	EAAHASH VARCHAR2(40), 
	AUDIT_CHANGER NUMBER, 
	AUDIT_ADM_CHANGER NUMBER, 
	 CONSTRAINT AVCON_USERS_STATU_000 CHECK (STATUS IN ('A', 'N')) ENABLE, 
	 CONSTRAINT USR_PK PRIMARY KEY (ID)
    
	 CONSTRAINT USR_INS_FK FOREIGN KEY (INS_ID)
	  REFERENCES INSTITUTES (ID) ENABLE
);
   COMMENT ON COLUMN USERS.ID IS 'Sequence=SEQ_USERS_ID,Label=User ID'
   COMMENT ON COLUMN USERS.NAME IS 'Label=Name'
   COMMENT ON COLUMN USERS.LASTNAME IS 'Label=Lastname'
   COMMENT ON COLUMN USERS.EMAIL IS 'Label=E-mail'
   COMMENT ON COLUMN USERS.URL IS 'Label=WWW Home Page'
   COMMENT ON COLUMN USERS.STATUS IS 'Label=Validation'
   COMMENT ON COLUMN USERS.PASSWORD IS 'Label=Password'
   COMMENT ON COLUMN USERS.MAILING IS 'Label=Included in mailing lists'
   COMMENT ON COLUMN USERS.INS_ID IS 'Label=Institute'
   COMMENT ON COLUMN USERS.GENDER IS 'Label=Gender,vallist=,M,F'
   COMMENT ON COLUMN USERS.NATIONALITY IS 'Label=Present nationality,List=SELECT code, name FROM countries ORDER BY name'
   COMMENT ON COLUMN USERS.BIRTH IS 'Label=Birth date '
   COMMENT ON COLUMN USERS.COMP_1 IS 'Label=Competence 1,List=SELECT code, description FROM competence ORDER BY description'
   COMMENT ON COLUMN USERS.COMP_2 IS 'Label=Competence 2 List=SELECT code, description FROM competence ORDER BY description'
   COMMENT ON COLUMN USERS.RESEARCHER_TYPE IS 'Label=Researcher type,deflist=Research Fellow,Academic Staff,Post Doctoral Researcher,Doctoral Research Student,Master Research Student,Undergraduate Student,Technician,SESAME Staff,vallist=REF,ACS,PDOC,DOCR,MRS,UND,TECH,SES'
   COMMENT ON COLUMN USERS.NEW_USER IS 'Label=New user'
   COMMENT ON COLUMN USERS.BIRTH_CITY IS 'Label=Birth place'
   COMMENT ON COLUMN USERS.BIRTH_CNT_ID IS 'Label=Birth country,List=SELECT code, name FROM countries ORDER BY name'
   COMMENT ON COLUMN USERS.HOME_ADDR IS 'Label=Home address'
   COMMENT ON COLUMN USERS.HOME_CITY IS 'Label=City'
   COMMENT ON COLUMN USERS.HOME_CNT_ID IS 'Label=Country,List=SELECT code, name FROM countries ORDER BY name'
   COMMENT ON COLUMN USERS.HOME_ZIP IS 'Label=ZIP code'
--------------------------------------------------------

CREATE TABLE USERS_DETAILS 
   (	ID NUMBER NOT NULL ENABLE, 
	ENTITY VARCHAR2(20), 
	PHONE VARCHAR2(30), 
	UDT_PUBLIC VARCHAR2(1), 
	LOCATION VARCHAR2(20), 
	UDT_COMMENT VARCHAR2(80), 
	UDT_TYPE VARCHAR2(1) NOT NULL ENABLE, 
	USR_ID NUMBER NOT NULL ENABLE, 
	PRIORITY NUMBER, 
	PHONE_ID NUMBER, 
	 CONSTRAINT AVCON_USERS_UDT_T_000 CHECK (UDT_TYPE IN ('W','H','F','M','P','O')) ENABLE, 
	 CONSTRAINT AVCON_USERS_UDT_P_000 CHECK (UDT_PUBLIC IN ('Y', 'N')) ENABLE, 
	 CONSTRAINT UDT_PK PRIMARY KEY (ID)
    
	 CONSTRAINT UDT_USR_FK FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE, 
	 CONSTRAINT USERS_DETAILS_FK1 FOREIGN KEY (PHONE_ID)
	  REFERENCES KEY_PHONES (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE USER_INFOS 
   (	ID NUMBER, 
	VIEWED DATE NOT NULL ENABLE, 
	INF_ID NUMBER, 
	USR_ID NUMBER, 
	 CONSTRAINT PK_USER_INFOS PRIMARY KEY (ID)
    
	 CONSTRAINT FK_USRINF_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE VIDEOS 
   (	ID NUMBER, 
	DESCRIPTION VARCHAR2(200), 
	FACILITY VARCHAR2(1), 
	ENABLED VARCHAR2(1), 
	ITEM_TYPE VARCHAR2(1)
);
--------------------------------------------------------

CREATE TABLE VIDEO_WATCHING 
   (	ID NUMBER, 
	USR_ID NUMBER, 
	VISION_DATE DATE, 
	VIDEO_ID NUMBER NOT NULL ENABLE, 
	VIGILANCE_ID NUMBER, 
	 CONSTRAINT FK_VIDEO_WATCHING_USR_ID FOREIGN KEY (USR_ID)
	  REFERENCES USERS (ID) ENABLE
);
--------------------------------------------------------

CREATE TABLE VISITORS -- Description: Deatails of visitors and their visit 
   (	ID NUMBER NOT NULL ENABLE, 
	REQ_DATE DATE DEFAULT sysdate NOT NULL ENABLE, 
	FAMILY_NAME VARCHAR2(60), 
	FIRST_NAME VARCHAR2(200) NOT NULL ENABLE, 
	AFFILIATION VARCHAR2(2000) NOT NULL ENABLE, 
	COUNTRY VARCHAR2(100) NOT NULL ENABLE, 
	EMAIL VARCHAR2(100) NOT NULL ENABLE, 
	DATE_OF_ARRIVAL DATE NOT NULL ENABLE, 
	TIME_OF_ARRIVAL VARCHAR2(100), 
	DATE_OF_DEPARTURE DATE, 
	NOTES_COMMENTS VARCHAR2(2000), 
	TIME_OF_DEPARTURE VARCHAR2(100), 
	USER_ID NUMBER(5,0) DEFAULT 1001 NOT NULL ENABLE, 
	CHECKEDIN VARCHAR2(100), 
	BARCODE NUMBER(5,0) DEFAULT NULL NOT NULL ENABLE, 
	 CONSTRAINT VISITORS_PK PRIMARY KEY (ID)
);
--------------------------------------------------------

CREATE TABLE VISITS 
   (	CLASSROOM VARCHAR2(40), 
	END_NOTE VARCHAR2(4000), 
	ID NUMBER NOT NULL ENABLE, 
	INSTITUTE_ADDRESS VARCHAR2(40), 
	INSTITUTE_CITY VARCHAR2(40), 
	INSTITUTE_CNT_ID VARCHAR2(4), 
	INSTITUTE_NAME VARCHAR2(100), 
	INSTITUTE_TYPE VARCHAR2(5), 
	INSTITUTE_ZIP VARCHAR2(30), 
	VISIT_LANGUAGE_ID VARCHAR2(2), 
	OTHER_INFORMATION VARCHAR2(400), 
	REF_EMAIL VARCHAR2(80), 
	REF_FAX VARCHAR2(40), 
	REF_LASTNAME VARCHAR2(40), 
	REF_NAME VARCHAR2(40), 
	REF_TEL VARCHAR2(40), 
	STATUS VARCHAR2(2), 
	SUBMISSION_DATE DATE NOT NULL ENABLE, 
	VISITORS NUMBER, 
	VISIT_DATE DATE, 
	PREF_LANGUAGE VARCHAR2(2), 
	APPROVER_ID NUMBER, 
	LOCAL_CONTACT_ID NUMBER, 
	INSTITUTE_PROVINCE VARCHAR2(2), 
	INSTITUTE_TOWN VARCHAR2(50), 
	BEGIN_DATE DATE, 
	END_DATE DATE, 
	GUIDES NUMBER, 
	EDIT_LINK VARCHAR2(32), 
	CANTEEN VARCHAR2(1), 
	MEALS NUMBER
);
--------------------------------------------------------

CREATE TABLE VUO_COL_COMMENTS 
   (	TABLE_NAME VARCHAR2(40) NOT NULL ENABLE, 
	COLUMN_NAME VARCHAR2(40) NOT NULL ENABLE, 
	COMMENTS VARCHAR2(4000), 
	 CONSTRAINT PK_TABLE_NAME_COLUMN_NAME PRIMARY KEY (TABLE_NAME, COLUMN_NAME)
);
--------------------------------------------------------

CREATE TABLE VUO_COL_COMMENTS_BCK_MZ -- Description: Backup
   (	TABLE_NAME VARCHAR2(40) NOT NULL ENABLE, 
	COLUMN_NAME VARCHAR2(40) NOT NULL ENABLE, 
	COMMENTS VARCHAR2(4000)
);
--------------------------------------------------------

CREATE TABLE VUO_COL_COMMENTS_BCK_OCT_17 -- Description: Backup
   (	TABLE_NAME VARCHAR2(40) NOT NULL ENABLE, 
	COLUMN_NAME VARCHAR2(40) NOT NULL ENABLE, 
	COMMENTS VARCHAR2(4000)
);
--------------------------------------------------------

CREATE TABLE VUO_COL_COMMENTS_BK -- Description: Backup
   (	TABLE_NAME VARCHAR2(40) NOT NULL ENABLE, 
	COLUMN_NAME VARCHAR2(40) NOT NULL ENABLE, 
	COMMENTS VARCHAR2(4000)
);
--------------------------------------------------------

CREATE TABLE VUO_PREF 
   (	ID VARCHAR2(10) NOT NULL ENABLE, 
	DT_BEGIN DATE, 
	DT_END DATE, 
	LABEL VARCHAR2(255), 
	SEMESTER NUMBER, 
	FACILITY VARCHAR2(1)
);
   COMMENT ON COLUMN VUO_PREF.DT_BEGIN IS 'Label=Start date'
   COMMENT ON COLUMN VUO_PREF.DT_END IS 'Label=End date'
   COMMENT ON COLUMN VUO_PREF.LABEL IS 'Label=Label to display'
--------------------------------------------------------

CREATE TABLE VUO_SESSIONS 
   (	COOKIE_VAL VARCHAR2(32) NOT NULL ENABLE, 
	USR_ID NUMBER, 
	REAL_USR_ID NUMBER, 
	LOGIN_DATE DATE, 
	LASTOP_DATE DATE, 
	LOGOUT_DATE DATE, 
	UMBRELLA_UID VARCHAR2(50), 
	UMBRELLA_EAAKEY VARCHAR2(40), 
	 CONSTRAINT SYS_C0048755 UNIQUE (COOKIE_VAL)
);
--------------------------------------------------------

CREATE TABLE XRDCONTINUATIONS 
   (	ID NUMBER NOT NULL ENABLE, 
	SAMPLE VARCHAR2(64) NOT NULL ENABLE, 
	USED_SHIFTS NUMBER NOT NULL ENABLE, 
	TEMPERATURE NUMBER NOT NULL ENABLE, 
	PLATE_SIZE NUMBER NOT NULL ENABLE, 
	ROTATION_ANGLE NUMBER NOT NULL ENABLE, 
	EXPOSURE_TIME NUMBER NOT NULL ENABLE, 
	RESOLUTION NUMBER NOT NULL ENABLE, 
	PROCESSING_PROGRAM VARCHAR2(64) NOT NULL ENABLE, 
	REFLECTIONS NUMBER NOT NULL ENABLE, 
	RSYM NUMBER NOT NULL ENABLE, 
	RSYM_HRC NUMBER NOT NULL ENABLE, 
	COMPLETENESS NUMBER NOT NULL ENABLE, 
	HEAVY_ATOM VARCHAR2(1) NOT NULL ENABLE, 
	ANOMALOUS_SIGNAL VARCHAR2(1) NOT NULL ENABLE, 
	INTERPRETABLE_PATTERSON VARCHAR2(1) NOT NULL ENABLE, 
	STRUCTURE_SOLVED VARCHAR2(1) NOT NULL ENABLE, 
	HELPED_MODEL_BUILDING VARCHAR2(1) NOT NULL ENABLE, 
	PUBBLICATIONS VARCHAR2(2048) NOT NULL ENABLE, 
	PROGRESS VARCHAR2(2048) NOT NULL ENABLE, 
	PROP_ID NUMBER NOT NULL ENABLE, 
	UNIQUE_REFLECTIONS NUMBER, 
	 CONSTRAINT XRDC_PK PRIMARY KEY (ID)
    
	 CONSTRAINT XRDC_PROP_FK FOREIGN KEY (PROP_ID)
	  REFERENCES PROPOSALS (ID) ENABLE
);
--------------------------------------------------------